<?php

$customers = $db->orderby('id', 'DESC')->getValue(T_CUSTOMERS, 'COUNT(*)');
$happy_clients = number_format($customers);

?>
<article class="padding-top-bottom">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-7 pr-5 mb-5 mb-lg-0">
				<div class="button">
					<span class="actual-text">&nbsp;<?php echo $wo['config']['siteTitle']; ?>&nbsp;</span>
					<span class="hover-text" aria-hidden="true">&nbsp;<?php echo $wo['config']['siteTitle']; ?>&nbsp;</span>
				</div>
				<h1>Corporate Profile</h1>
				<p> With the objective to provide urban inhabitants with access to modern homes, Civic Moonhill began its journey in 2020. Since its inception, we have worked diligently to provide the most modern facilities to our projects. </p>
				<p> Along with the government's efforts, we have played a vital role in addressing the growth of housing crisis. We give due importance in focusing our customary corporate ethics as well as our social obligations. </p>
				
				<a href="<?php echo $wo['config']['site_url']; ?>/civic-moonhill" class="cta-phn con-btn big-circle mt-lg-5">
				<span></span>
				<span></span>
				<span></span>
				<span></span>Projects!</a>
			</div>
			<div class="col-lg-5">
				<div class="rectangular-border">
					<div class="mask-img rectangular-mask">
						<img class="" src="<?php echo $wo['config']['theme_url'];?>/img/bg/05_katha_plot_civic_moon_hill.webp" alt="Land developer company in Dhaka">
					</div>
				</div>
				<div class="box-absolute">
					<a class="link" href="<?php echo $wo['config']['site_url'] . '/happy-clients'; ?>">
						<div class="d-flex align-items-center">
							<span class="word-text has-animate-number counter mr-1"><?php echo $happy_clients * 2; ?></span>
							<span class="font-medium">+</span>
						</div>
						<span class="title-block">Happy Clients</span>
					</a>
				</div>
			</div>
		</div>
	</div>
</article>
<?php echo Wo_LoadPage('about-us/include/mission_vision'); ?>