<div class="ms-auto button_flex_middle">
<?php if (check_permission('update-leave') || Wo_IsAdmin() || Wo_IsModerator()) { ?>
<div id="dataSheet_download" style="margin-right: 10px;">
	<div class="dt-buttons btn-group">
		<button class="btn btn-outline-secondary buttons-excel buttons-html5" onclick="download_report()" type="button" title="Export to Excel">
			<span>
				<svg xmlns="http://www.w3.org/2000/svg" width="15" height="18" viewBox="0 0 18 24">
					<path fill="currentColor" d="M20.34,4.59,16.41.66A2.28,2.28,0,0,0,14.82,0H5.25A2.25,2.25,0,0,0,3,2.25v19.5A2.25,2.25,0,0,0,5.25,24h13.5A2.25,2.25,0,0,0,21,21.75V6.19A2.27,2.27,0,0,0,20.34,4.59ZM18.57,6H15V2.44ZM5.25,21.75V2.25h7.5V7.13a1.12,1.12,0,0,0,1.12,1.12h4.88v13.5ZM15.19,10.5H13.84a.55.55,0,0,0-.49.3A24.54,24.54,0,0,0,12,13.5c-.65-1.36-.32-.81-1.34-2.7a.56.56,0,0,0-.49-.3H8.81a.56.56,0,0,0-.48.85L10.5,15,8.33,18.66a.56.56,0,0,0,.48.84h1.36a.56.56,0,0,0,.49-.29A23.15,23.15,0,0,0,12,16.5c.7,1.42.28.75,1.34,2.71a.57.57,0,0,0,.5.29h1.35a.56.56,0,0,0,.48-.84L13.5,15c0-.05,1.42-2.36,2.17-3.65A.56.56,0,0,0,15.19,10.5Z" transform="translate(-3)"></path>
				</svg>
			</span>
		</button>
	</div>
</div>
<?php } ?>
 <style>
	#dataSheet_download button.btn {
		border: 2px solid transparent;
		padding: 6px 2px;
		width: 40px;
		border-radius: 8px;
	}
	#dataSheet_download button.btn:hover {
		background: white;
		border: 2px solid #6c757d;
		color: #6c757d;
	}
	
 </style>
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary" onclick="apply_leave();">Apply Leave</button>
</div>