<?php
// echo 'LT: ' . date('Y-m-d H:i:s', 1729332433);
// echo '<br>';
// echo 'CT: ' . date('Y-m-d H:i:s', time());
// echo '<br>';
// echo 'T: ' . time();


    // // Get SMS records that have not been delivered, need to retry, and have not exceeded 3 attempts
    // $smsRecords = $db->where('status', 'Delivered', '!=')
                     // ->where('status', 'Failed', '!=')
                     // ->where('tried', 3, '<')
                     // ->where('last_tried', time(), '>=') // last_tried >= strtotime('-2 minutes')
                     // ->get(T_SMS, 5);
// echo '<pre>';
// print_r($smsRecords);
// echo '</pre>';

// print_r(sms_delivery('bw-rdC200794167136d38441d1'));
 if (check_permission('manage-sms') || Wo_IsAdmin() || Wo_IsModerator()) {}
// manage-sms
echo sms_update_report(); ?>
<!--start breadcrumb-->
<div class="page-breadcrumb d-flex align-items-center mb-3">
  <div class="breadcrumb-title pe-3">SMS Report</div>
  <?php echo Wo_LoadManagePage('sms_report/send_sms'); ?>
</div>

<!--end breadcrumb-->
<div class="mb-3">
	<div class="row row-cols-auto g-3">
		<div class="col">
		</div>
	</div>
</div>

<div class="row row-cols-1 row-cols-lg-2 row-cols-xxl-5">
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Current Balance</p>
					</div>
					<div class="ms-auto">
						<ion-icon name="bar-chart" role="img" class="md hydrated" aria-label="bar-chart"></ion-icon>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0" id="current_balance_elitbuzz">
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
						</h4>
						<small class="mb-0">Current balance is fetch from Elitbuzz</small>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">SMS</p>
					</div>
					<div class="ms-auto">
						<ion-icon name="bar-chart" role="img" class="md hydrated" aria-label="bar-chart"></ion-icon>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0" id="total_sms_elitbuzz">
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
						</h4>
						<small class="mb-0">Approx sms can be send</small>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Current Balance</p>
					</div>
					<div class="ms-auto">
						<ion-icon name="bar-chart" role="img" class="md hydrated" aria-label="bar-chart"></ion-icon>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0" id="current_balance_iglweb">
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
						</h4>
						<small class="mb-0">Current balance is fetch from IGL Web</small>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">SMS</p>
					</div>
					<div class="ms-auto">
						<ion-icon name="bar-chart" role="img" class="md hydrated" aria-label="bar-chart"></ion-icon>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0" id="total_sms_iglweb">
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
							<div class="spinner-grow spinner-grow-sm" role="status"> <span class="visually-hidden">Loading...</span> </div>
						</h4>
						<small class="mb-0">Approx sms can be send</small>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


    <!-- Your HTML code starts here -->

	<?php if (Wo_IsAdmin() || Wo_IsModerator()) { ?>
	<div class="attandence mb-3">
        <div class="select-panel d-flex justify-content-between">
                <select id="user_id" name="user_id" class="form-select w-auto wm-150" onchange="DataTableRefresh()">
                    <?php 
						$get_users = $db->where('active', '1')->orderBy('serial', 'ASC')->get(T_USERS);
						foreach ($get_users as $userlist) {
							$first_name = cleanName($userlist->first_name);
							echo '<option' . (isset($_COOKIE['sms_user']) && $_COOKIE['sms_user'] == $userlist->user_id ? ' selected' : '') . " value='{$userlist->user_id}'>{$first_name} {$userlist->last_name}</option>";
						}
                    ?>
                </select>
				<!-- Use flatpickr for date selection -->
				<input class="form-select w-auto ml-auto wm-150" type="text" id="date_start_end" name="date_start_end" placeholder="Select date range" readonly onchange="DataTableRefresh()" value="<?php echo urldecode($_COOKIE['start_end_sms']); ?>">
        </div>
    </div>
	<?php } else { ?>
		<div class="attandence mb-3">
			<div class="select-panel d-flex justify-content-between">
				<select id="user_id" name="user_id" class="form-select w-auto" style="visibility: hidden;">
					<option value="<?php echo $wo['user']['user_id'];?>" selected><?php echo $wo['user']['Name'];?></option>
				</select>
				
				<!-- Use flatpickr for date selection -->
				<input class="form-select w-auto ml-auto" type="text" id="date_start_end" name="date_start_end" placeholder="Select date range" readonly onchange="DataTableRefresh()" value="<?php echo urldecode($_COOKIE['start_end'] ?? '') ?: date('Y-m-01') . ' to ' . date('Y-m-t'); ?>">
			</div>
		</div>
	<?php } ?>
	

    <div class="card radius-10 w-100">
        <div class="card-body">
            <div class="table-responsive atten_container" id="atten_container">
                <table class="table align-middle mb-0 atten_container" id="invoiceTable" style="width: 100%;">
                    <thead class="table-light" style=" position: sticky; top: 0; background: white; ">
                        <tr>
                            <th style="width: 11px;">ID</th>
                            <th style="width: 11px;">Sender ID</th>
                            <th style="width: 21px;">To</th>
                            <th style="width: 21px;">Cost</th>
                            <th style="width: 21px;">Status</th>
                            <th style="width: 11px;">Time</th>
                            <th>Msg</th>
                        </tr>
                    </thead>
                    <tbody id="result"></tbody>
                </table>
            </div>
        </div>
    </div>
<?php echo Wo_LoadManagePage('sms_report/sendSMS_modal'); ?>
<script>
function send_sms_modal() {
	$(".send_sms_modal_btn").prop("disabled", true);
	$("#sendSMS-modal").modal('show');
}
$(document).ready(function() {
	// Initialize Flatpickr
	var flatpickrInstance = flatpickr('#date_start_end', {
		mode: 'range',
		dateFormat: 'Y-m-d',
		altFormat: 'F j, Y',
		altInput: false,
		allowInput: false,
		clickOpens: true,
		onChange: function(selectedDates, dateStr, instance) {
			// console.log(selectedDates);
			// // You can add additional logic here if needed
		},
		onReady: function(selectedDates, dateStr, instance) {
			// Add custom date range options to the Flatpickr container
			var datepickerContainer = instance.calendarContainer;

			var dateRangeOptions = [
				{ label: 'Today', range: [new Date(), new Date()] },
				{ label: 'Yesterday', range: [new Date(new Date().setDate(new Date().getDate() - 1)), new Date(new Date().setDate(new Date().getDate() - 1))] },
				{ label: 'This Month', range: [new Date(new Date().getFullYear(), new Date().getMonth(), 1), new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0)] },
				{ label: 'Last Month', range: [new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1), new Date(new Date().getFullYear(), new Date().getMonth(), 0)] },
			];

			dateRangeOptions.forEach(function(option) {
				var button = document.createElement('button');
				button.textContent = option.label;
				button.addEventListener('click', function() {
					flatpickrInstance.setDate(option.range);
					flatpickrInstance.close(); // Close Flatpickr instance
					DataTableReset();
				});

				datepickerContainer.prepend(button);
			});
		}
	});
	
    // Initialize DataTables without buttons
    var table = $('#invoiceTable').DataTable({
        "processing": true,
		"serverSide": true,
        "pageLength": 25,  // Set the default number of entries per page
        "ajax": {
            "url": Wo_Ajax_Requests_File() + '?f=bulk_sms&s=report',
            "type": "POST",
			"data": function (d) {
				// Include additional parameters for the AJAX request
				d.status_id = $('#status_id').val();
				d.user_id = $('#user_id').val();
				var dateRange = document.getElementById('date_start_end').value;
				// If date range is not selected, use the single selected date
				var dates = dateRange.split(' to ');
				var data_start = dates[0];
				var data_end = dates.length > 1 ? dates[1] : data_start;
				
				d.data_start = data_start;
				d.data_end = data_end;
				
			},
            "beforeSend": function(xhr) {
				$('#length_count').remove();
				$('#invoiceTable_length label').append('<span id="length_count"><span>');
                // Set opacity to 0 before the Ajax request
                $('#invoiceTable').css('opacity', .5);
            },
            "complete": function(xhr) {
				// Parse the JSON response
				var responseData = JSON.parse(xhr.responseText);
				// Access the recordsTotal value
				var recordsTotal = responseData.recordsTotal;
					
                // Set opacity to 1 after the Ajax request is complete
                $('#invoiceTable').css('opacity', 1);
                $('#length_count').html('of <b>' + recordsTotal + '</b>');
            }
        },
        "columns": [
            { "data": "id", "orderable": true },  // ID column is orderable
            { "data": "senderid", "orderable": false },
            { "data": "contacts", "orderable": false },
            { "data": "cost", "orderable": false },
            { "data": "status", "orderable": false },
            { "data": "time", "orderable": false },
            { "data": "msg", "orderable": false },
        ],
        "order": [],
        "language": {
            "emptyTable": "No data available in the table",
            "infoEmpty": "Showing 0 to 0 of 0 entries",
            "infoFiltered": "(filtered from _MAX_ total entries)",
            "zeroRecords": "No matching records found"
        },
		"rowCallback": function(row, data) {
			$(row).attr('data-id', data.id);
		}
    });
	
    // DataTableReset function to reset the DataTable
    window.DataTableReset = function() {
        table.ajax.reload();
    };
	
	window.DataTableRefresh = function() {
		table.ajax.reload(null, false); // Reload the DataTable

		// After reload, restore the state (including pagination)
		var state = table.state.loaded();
		if (state) {
			table.state.restore(state);
		}
	};
});
function get_sms_status() {
    $.ajax({
        type: "POST",
        url: Wo_Ajax_Requests_File() + '?f=bulk_sms&s=fetch_status',
        success: function (response) {
            if (response['status'] == 200) {
				$("#current_balance_elitbuzz").html(response['current_balance_elitbuzz']);
				$("#total_sms_elitbuzz").html(response['total_sms_elitbuzz']);
				
				$("#current_balance_iglweb").html(response['current_balance_iglweb']);
				$("#total_sms_iglweb").html(response['total_sms_iglweb']);
            } else {
				pos4_error_noti(response['message']);
			}
        }
    });
}
$(document).ready(function() {
	get_sms_status();
});
</script>