<script>
$(document).ready(function() {
    $(document).on("click", ".edit-post", function (e) {
        var data = 'Welcome to modal of native app...';
        if (window.AndroidApp) {
            window.AndroidApp.openModal(data);
        }
    });
});
</script>

<!---a href="#" class="edit-post">click here</a--->

<!--start breadcrumb-->
<div class="page-breadcrumb d-flex align-items-center mb-3" style="justify-content: space-between;">
  <div class="breadcrumb-title pe-3"><?php echo $wo['title']; ?></div>
        <div class="select-panel d-flex justify-content-between">
            <!-- Use flatpickr for date selection -->
            <input class="form-select w-auto" type="text" id="date_start_end" name="date_start_end" placeholder="Select date range" readonly onchange="DataTableReset()" value="<?php echo urldecode($_COOKIE['start_end2']); ?>">
        </div>
</div>
<!--end breadcrumb-->

<div class="mb-3">
	<div class="row row-cols-auto g-3">
		<div class="col">
		</div>
	</div>
</div>
<style>
tr:hover, tr:focus, tr:active {
    --bs-table-bg: #f3f3f3;
}
</style>
<?php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);




// // Insert notification
// $notification_user = '108';
// $insert_notif = $db->insert(NOTIFICATION, [
//     'subject' => 'Lead: ' . $rowData['full_name'],
//     'comment' => 'You have new leads from ' . $project_name,
//     'type'    => 'leads',
//     'url'     => '/management/leads?lead_id=' . $lead['id'],
//     'user_id' => $notification_user
// ]);

// // 1) Pull one “clean” remark per lead
// $latestRemarks = $db
//   ->where('is_system', 0)
//   ->where('lead_id', 3000, '>')
//   ->where('lead_id', 3500, '<')
//   // exclude any remark containing stray <small> or <strong> tags
//   ->where('remarks', '%<small>%',   'NOT LIKE')
//   ->where('remarks', '%<strong>%',  'NOT LIKE')
//   // make sure the newest remarks come first
//   ->orderBy('id', 'DESC')
//   // then collapse to one row per lead_id
//   ->groupBy('lead_id')
//   ->get(
//     T_REMARKS,
//     null,
//     ['lead_id', 'remarks']
//   );

// // 2) Loop and update each lead
// foreach ($latestRemarks as $row) {
//     // echo $row->remarks;
//     $db->where('lead_id', $row->lead_id)
//       ->update(T_LEADS, [
//          'remarks' => $row->remarks
//       ]);
// }



// Global $android;
// echo $_COOKIE['user_id2'] . '<br />';
// echo($android['version']);
// $insert_notif = $db->insert(NOTIFICATION, [
//     'subject' => 'Lead: Aminul Islam',
//     'comment' => 'You have new leads from Test',
//     'type'    => 'leads',
//     'url'     => '/management/leads',
//     'user_id' => 1
// ]);

$get_users = $db->orderBy('position', 'ASC')->where('active', '1')->where('banned', '0')->where('is_team_leader', '0')->where('leader_id', '0', '>')->get(T_USERS, null, ['user_id']);
$msg_type = 'lead';
// Get the start and end of the current month
$month_start = strtotime('first day of this month 00:00:00');
$month_end = strtotime('last day of this month 23:59:59');

echo Wo_LoadManagePage('view_notif/content');
function count_leads2($status) {
    Global $db, $wo;

    // Get start and end date from cookie
    $starttoend = isset($_COOKIE['start_end2']) ? urldecode($_COOKIE['start_end2']) : '';

    if (!empty($starttoend)) {
        $exp = explode(' to ', $starttoend);
        $date_start = $exp[0] ?? '';
        $date_end = $exp[1] ?? '';
    }
    // If $date_start is empty, set it to the first day of the current month
    if (empty($date_start)) {
        $date_start = date('Y-m-01'); // First day of the current month
    }

    // If $date_end is empty, set it to the last day of the current month
    if (empty($date_end)) {
        $date_end = $date_start; // Last day of the current month
    }

    // Append time for correct timestamp conversion
    $date_start .= ' 00:00:00';
    $date_end .= ' 23:59:59';
    
    $start_timestamp = strtotime($date_start);
    $end_timestamp = strtotime($date_end);

    // Applying conditions manually without closure
    if (Wo_IsAdmin() || Wo_IsModerator() || check_permission('manage-leads')) {
        $db->where('status', $status)->where('assigned', 0, '>')->where('created', $start_timestamp, '>=')->where('created', $end_timestamp, '<=')->orWhere('member', 0, '>');
    } elseif ($wo['user']['is_team_leader'] == true) {
        $db->where('status', $status)->where('assigned', $wo['user']['user_id'])->where('created', $start_timestamp, '>=')->where('created', $end_timestamp, '<=');
    } else {
        $db->where('status', $status)->where('assigned', $wo['user']['leader_id'])->where('created', $start_timestamp, '>=')->where('created', $end_timestamp, '<=')->orWhere('member', $wo['user']['user_id']);
    }

    return $db->where('status', $status)
              ->where('created', $start_timestamp, '>=')
              ->where('created', $end_timestamp, '<=')
              ->getValue(T_LEADS, 'COUNT(*)');
}


?>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xxl-6">
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Not Started/Pending</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo count_leads2(0) + count_leads2(4); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Not Interested</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo count_leads2(9) + count_leads2(10) + count_leads2(11) + count_leads2(12); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Positive</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo count_leads2(14); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Visit Done</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo count_leads2(6); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Sale Done</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo count_leads2(5); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card radius-10">
			<div class="card-body">
				<div class="d-flex align-items-start gap-2">
					<div>
						<p class="mb-0 fs-6">Remaining Leave</p>
					</div>
					<div class="ms-auto">
						<i class='fadeIn animated bx bx-bar-chart fs-5' ></i>
					</div>
				</div>
				<div class="d-flex align-items-center mt-3">
					<div>
						<h4 class="mb-0"><?php echo str_replace('-', 'Overused: -', remaining_leave($wo['user']['user_id'])); ?></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Your HTML code starts here -->
<div class="card radius-10 w-100">
    <div class="card-body">
        <div class="table-responsive mt-2">
            <table id="invoiceTable" class="table align-middle mb-0" style="width: 100%;">
                <thead class="table-light">
					<tr>
						<th style="width: 45px;">Name</th>
						<th style="width: 45px;">Leader</th>
						<?php 
						function lead_count($db, $user_id, $status, $date_start = '', $date_end = '') {
                            // Get start and end date from cookie
                            $starttoend = isset($_COOKIE['start_end2']) ? urldecode($_COOKIE['start_end2']) : '';
                        
                            if (!empty($starttoend)) {
                                $exp = explode(' to ', $starttoend);
                                $date_start = $exp[0] ?? '';
                                $date_end = $exp[1] ?? '';
                            }
                            // If $date_start is empty, set it to the first day of the current month
                            if (empty($date_start)) {
                                $date_start = date('Y-m-01'); // First day of the current month
                            }
                        
                            // If $date_end is empty, set it to the last day of the current month
                            if (empty($date_end)) {
                                $date_end = $date_start; // Last day of the current month
                            }
                        
                            // Append time for correct timestamp conversion
                            $date_start .= ' 00:00:00';
                            $date_end .= ' 23:59:59';
                            
                            $start_timestamp = strtotime($date_start);
                            $end_timestamp = strtotime($date_end);

							$user_data = Wo_UserData($user_id);
							if ($user_data['is_team_leader']) {
								return $db->where('assigned', $user_id)
										  ->where('status', $status)
										  ->where('member', 0, '<=')
										  ->where('created', $start_timestamp, '>=')
										  ->where('created', $end_timestamp, '<=')
										  ->getValue(T_LEADS, 'COUNT(*)');
							} else {
								return $db->where('assigned', '0', '>')
										  ->where('status', $status)
										  ->where('member', $user_id)
										  ->where('created', $start_timestamp, '>=')
										  ->where('created', $end_timestamp, '<=')
										  ->getValue(T_LEADS, 'COUNT(*)');
							}
						}

						$get_status = array(
							'0' => 'Not Started/Pending',
							'9' => 'Not Interest',
							'14' => 'Positive',
							'6' => 'Visit Done',
							'5' => 'Sale Done',
						);

						foreach ($get_status as $key => $status) {
							echo '<th style="width: 65px;" class="text-center">' . htmlspecialchars($status) . '</th>';
						}
						?>
					</tr>
				</thead>
				<tbody>
					<?php 
					$get_users = $db->orderBy('position', 'ASC')
									->where('is_team_leader', '1')
									->orWhere('leader_id', '0', '>')
									->where('active', '1')
									->where('banned', '0')
									->where('admin', '0')
									->get(T_USERS);

					foreach ($get_users as $user) {
						?>
						<tr role="row" class="odd" data-id="<?php echo htmlspecialchars($user->user_id); ?>" <?php echo ($user->is_team_leader) ? 'style="--bs-table-bg: #f3f3f3;"' : ''; ?>>
							<td style="font-weight: 500"><img src="/<?php echo htmlspecialchars($user->avatar); ?>" class="user-img" style=" width: 24px; height: 24px; border-radius: 35px; margin-right: 8px; "><?= htmlspecialchars(ucfirst($user->first_name) . (!empty($user->last_name) ? ' ' . ucfirst($user->last_name) : '')); ?></td>
							<td>
								<?php
								if ($user->is_team_leader) {
									echo 'Team Leader';
								} else if ($user->leader_id > 0) {
									$leader_info = Wo_UserData($user->leader_id);
									echo htmlspecialchars($leader_info['name']);
								}
								?>
							</td>
							<?php
							foreach ($get_status as $key => $status) {
							    if ($key ==  0) {
								    echo '<td style="width: 65px;" class="text-center">' . htmlspecialchars(lead_count($db, $user->user_id, 4) + lead_count($db, $user->user_id, 0)) . '</td>';
							    } elseif ($key == 9) {
								    echo '<td style="width: 65px;" class="text-center">' . htmlspecialchars(lead_count($db, $user->user_id, 9) + lead_count($db, $user->user_id, 10) + lead_count($db, $user->user_id, 11) + lead_count($db, $user->user_id, 12)) . '</td>';
							    } else {
								    echo '<td style="width: 65px;" class="text-center">' . htmlspecialchars(lead_count($db, $user->user_id, $key)) . '</td>';
							    }
							}
							?>
						</tr>
					<?php } ?>
				</tbody>
            </table>
        </div>
    </div>
</div>

<script>
function setCookie(name, value, days = 0, path = '/', domain = '', secure = false) {
    let cookieString = `${encodeURIComponent(name)}=${encodeURIComponent(value)}`;

    if (days) {
        const date = new Date();
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        cookieString += `; expires=${date.toUTCString()}`;
    }

    if (path) {
        cookieString += `; path=${path}`;
    }

    if (domain) {
        cookieString += `; domain=${domain}`;
    }

    if (secure) {
        cookieString += `; secure`;
    }

    document.cookie = cookieString;
}

var date_start_end = document.getElementById('date_start_end');
date_start_end.addEventListener('change', function handleChange(event) {
	var targeted_value = event.target.value;
	setCookie('start_end2', targeted_value, 7);
	SMColibri.spa_load("<?php echo(Wo_LoadManageLinkSettings('dashboard')); ?>?period=" + targeted_value);
});
date_start_end.focus();
			
$(document).ready(function() {
	// Initialize Flatpickr
	var flatpickrInstance = flatpickr('#date_start_end', {
		mode: 'range',
		dateFormat: 'Y-m-d',
		altFormat: 'F j, Y',
		altInput: false,
		allowInput: false,
		clickOpens: true,
		onChange: function(selectedDates, dateStr, instance) {
			// console.log(selectedDates);
			// // You can add additional logic here if needed
		},
		onReady: function(selectedDates, dateStr, instance) {
			// Add custom date range options to the Flatpickr container
			var datepickerContainer = instance.calendarContainer;

			var dateRangeOptions = [
				{ label: 'Today', range: [new Date(), new Date()] },
				{ label: 'Yesterday', range: [new Date(new Date().setDate(new Date().getDate() - 1)), new Date(new Date().setDate(new Date().getDate() - 1))] },
				{ label: 'This Month', range: [new Date(new Date().getFullYear(), new Date().getMonth(), 1), new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0)] },
				{ label: 'Last Month', range: [new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1), new Date(new Date().getFullYear(), new Date().getMonth(), 0)] },
			];

			dateRangeOptions.forEach(function(option) {
				var button = document.createElement('button');
				var date_start_end = document.getElementById('date_start_end');
				button.textContent = option.label;
				button.addEventListener('click', function() {
					flatpickrInstance.setDate(option.range);
					flatpickrInstance.close(); // Close Flatpickr instance
					var date_value = date_start_end.value;
					setCookie('start_end2', date_value, 7);
					SMColibri.spa_load("<?php echo(Wo_LoadManageLinkSettings('dashboard')); ?>?period=" + date_value);
				});

				datepickerContainer.prepend(button);
			});
		}
	});
});
</script>