<link rel="stylesheet"
    href="<?php echo $wo['config']['theme_url'];?>/css/home.css?version=<?php echo $wo['config']['version']; ?>"
    type="text/css">

<?php
// 0) Fetch your slides
$sliders = $db->orderBy('position', 'ASC')->get(T_HOME_SLIDER);
?>

<section class="has_ma_el_bg_slider elementor-section elementor-top-section elementor-element elementor-element-2195c5d6 elementor-section-full_width elementor-section-height-default elementor-section-height-default jltma-glass-effect-no" data-id="2195c5d6" data-element_type="section">
  <div class="elementor-container elementor-column-gap-no">
    <div class="has_ma_el_bg_slider elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-a1b38c jltma-glass-effect-no" data-id="a1b38c" data-element_type="column">
      <div class="elementor-widget-wrap elementor-element-populated e-swiper-container">
        <div class="elementor-element elementor-element-4c50e34a elementor--h-position-center elementor--v-position-middle elementor-arrows-position-inside elementor-pagination-position-inside jltma-glass-effect-no elementor-widget elementor-widget-slides e-widget-swiper" data-id="4c50e34a" data-element_type="widget" data-settings='{"autoplay_speed":2500,"transition_speed":700,"navigation":"both","autoplay":"yes","pause_on_hover":"yes","pause_on_interaction":"yes","infinite":"yes","transition":"slide"}' data-widget_type="slides.default">
          <div class="elementor-widget-container">
            <div class="elementor-swiper">
              <div class="elementor-slides-wrapper elementor-main-swiper swiper" role="region" aria-roledescription="carousel" aria-label="Slides" dir="ltr" data-animation="fadeInRight">
                <div class="swiper-wrapper elementor-slides" id="swiper-wrapper-9857473904f6a9e1" aria-live="off">
                  <?php foreach ($sliders as $idx => $slide): ?>
                    <div
                      class="elementor-repeater-item-<?php echo $slide->id ?> swiper-slide"
                      data-swiper-slide-index="<?php echo $idx ?>"
                    >
                      <div
                        class="swiper-slide-bg"
                        role="img"
                        style="background-image:url('<?php echo htmlspecialchars($slide->image, ENT_QUOTES) ?>')"
                      ></div>
                      <div class="swiper-slide-inner">
                        <div class="swiper-slide-contents">
                          <!-- you can inject caption/title here if you like -->
                        </div>
                      </div>
                    </div>
                  <?php endforeach; ?>
                </div>
                <div class="elementor-swiper-button elementor-swiper-button-prev">
                  <i class="eicon-chevron-left"></i>
                </div>
                <div class="elementor-swiper-button elementor-swiper-button-next">
                  <i class="eicon-chevron-right"></i>
                </div>
                <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets swiper-pagination-horizontal"></div>
                <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Slides end -->


<iframe src="ads/728x90_v1.html" style="width: 100%; max-width: 728px; height: 90px; border: 0; overflow: hidden; margin: auto; display: flex ;" scrolling="no"></iframe>

<div class="intro-text text-center area-padding">
    <div class="container-fluid">
        <div class="row">
            <article class="col-12">
                <div class="area-heading">
                    <span>Civic Group</span>
                    <h1 class="section-heading">Leading Real Estate Company in Bangladesh</h1>
                </div>
                <p class="para-padding"> Founded in 2007, CIVIC GROUP is one of the most respected Group of Company in
                    Bangladesh, engaged in designing &amp; developing luxurious housing &amp; commercial projects,
                    tourism, building construction services, health and agriculture industry. We are one of the leading
                    Real Estate company in Bangladesh, envisions itself to lead the real estate sector by keeping
                    abreast with the new-age industry standards and thereby being an inspiration to its competitors.
                </p>
                <p class="para-padding mb-80"> Since inception, we are working towards creating better living spaces for
                    the people of Bangladesh. And has been continually building projects which are a balanced
                    composition of peaceful neighborhood, comfort, security and eloquent designs. This is quite evident
                    as the firm has earned a huge trust among its customers who keep looking forward to its upcoming
                    projects. We've created defining landmarks that have set new standards in real estate development
                    for more than a decade in Bangladesh. Our projects are ever growing vibrant life spaces for
                    thousands of satisfied families. </p>
                <div class="borders border-one">
                    <a href="/about-us" class="default-btn"> Explore About Us &gt;</a>
                </div>
            </article>
        </div>
    </div>
</div>

<section class="area-padding bg-one">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="area-heading text-center">
                    <h3 class="section-heading">Our Mission</h3>
                </div>
                <div class="content-box">
                    <p>As a quality-focused real estate company, we've achieved several notable milestones, including
                        earning the trust of our esteemed clients, recognition from industry experts, and acknowledgment
                        from international organizations. Our achievements include serving a significant number of
                        customers, completing numerous projects, and managing a substantial portfolio of ongoing and
                        upcoming ventures.</p>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="area-heading text-center">
                    <h3 class="section-heading">Our Vision</h3>
                </div>
                <div class="content-box">
                    <p>As a quality-focused real estate company, we've achieved several notable milestones, including
                        earning the trust of our esteemed clients, recognition from industry experts, and acknowledgment
                        from international organizations. Our achievements include serving a significant number of
                        customers, completing numerous projects, and managing a substantial portfolio of ongoing and
                        upcoming ventures.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- HTML -->
<div class="area-padding">
    <section class="container" id="projects">
        <div class="row">
            <div class="col-12 mb-25 text-center">
                <h2 class="section-heading"><b>Projects in Purbachal and Basundhara R/A</b></h2>
            </div>

            <!-- Tabs -->
            <div class="col-12 tab-area">
                <ul class="nav nav-tabs" id="propertyTab">
                    <li class="nav-item">
                        <a class="nav-link cursor-pointer active" data-filter="all">All</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-filter="land">Land Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-filter="apartment">Apartment Projects</a>
                    </li>
                </ul>

                <!-- Project Grid -->
                <div class="row mt-4 project-grid-gap">
                    <?php
						$projects = $db->where('active', '1')->get(T_PROJECTS);
						foreach ($projects as $project) {
							$project_data = json_decode($project->additional, true) ?: [];
                            unset($project->additional);
                            
							echo Wo_LoadPage('home/includes/product-lists', [
								'project'        => $project,
								'project_data' => $project_data
							]);
						}
					?>
                </div><!-- /.row -->
            </div><!-- /.tab-area -->
        </div><!-- /.row -->
    </section>
</div>

<section class="area-padding">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="area-heading text-center ">
                    <div class="section-heading">Our Sister Concerns</div>
                </div>
                <div class="row sister-grid">
                    <div class="col-12 col-sm-12 col-lg-6">
                        <div class="sister-item">
                            <h4>Civic Real Estate Ltd.</h4>
                            <p>Project: Civic Moon Hill</p>
                            <p>Adjacent to Purbachal 27th & 28th no Sector</p>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-lg-6">
                        <div class="sister-item">
                            <h4>Civic Design &amp; Development Ltd.</h4>
                            <p>Project: Civic Hill Town</p>
                            <p>Adjacent to Purbachal 30th no Sector</p>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-lg-6">
                        <div class="sister-item">
                            <h4>Civic Autos Mobiles</h4>
                            <p>Project: Car Dealership (Car/Parts Import)</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <img src="/themes/civicgroup/img/sister-concerns.jpg" alt="Civic Group Sister Concerns" loading="lazy"
                    width="690" height="400">
            </div>
        </div>
    </div>
</section>
<style>
/* CSS */
.civic-card {
    background: #fff;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    height: 100%;
}

.civic-card-thumb {
    position: relative;
}

.project-grid-gap {
    gap: 25px 0;
}

.civic-card-thumb img {
    width: 100%;
    display: block;
}

.civic-card-tags {
    position: absolute;
    top: 12px;
    left: 12px;
    display: flex;
    gap: 6px;
    justify-content: space-between;
    right: 12px;
}

.civic-card-tags .status {
    border-color: #fff;
    background: #fff;
    color: #1a1a1a;
    text-decoration: none;
    display: inline-block;
    padding: 2.5px 10px;
    border-radius: 20px;
    font-size: 13px;
    transition: .2s all ease-in-out;
    font-weight: 500;
    line-height: 1;
    box-shadow: 0 4px 12px rgb(0 0 0 / 4%);
}

.civic-card-tags .status:hover {
    border-color: #1a1a1a;
    background: #1a1a1a;
    color: rgb(255, 255, 255);
}

/* 
.civic-card-tags .ongoing {
    background: #0066cc;
}

.civic-card-tags .sold {
    background: #cc0000;
} */

.civic-card-fav {
    position: absolute;
    bottom: 12px;
    right: 12px;
}

.fav-btn {
    background: rgba(255, 255, 255, 0.8);
    border: none;
    padding: 5px 6px;
    border-radius: 50%;
    cursor: pointer;
}

.civic-card-body {
    padding: 16px;
    display: flex;
    flex-direction: column;
}

.civic-title {
    font-size: 17px;
    font-weight: 700;
    transition: .2s all ease-in-out;
    color: #333
}

.civic-title a {
    color: #333;
    text-decoration: none;
}

.civic-title a:hover {
    color: #0066cc;
    text-decoration: none;
}

.civic-address {
    font-size: 14px;
    color: #666;
    display: flex;
    align-items: center;
    margin: 0 0 5px;
}

.civic-address:hover {
    color: #0066cc;
    text-decoration: none;
}

.pin-icon {
    width: 16px;
    height: 16px;
    fill: #666;
    margin-right: 4px;
}

.civic-type {
    color: var(--rh-global-color-primary);
    display: inline-block;
    margin-bottom: 10px;
}

.civic-type small {
    font-size: 14px;
    font-weight: 600;
}

.civic-type a {
    color: rgb(37, 37, 37);
    text-decoration: none;
}

.civic-type a:hover {
    color: #0066cc;
    text-decoration: none;
}

.civic-price-meta {
    margin-top: auto;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    -moz-column-gap: 10px;
    column-gap: 10px;
    align-items: center;
}

.civic_prop_card_meta_wrap {
    display: inline-flex;
    flex-wrap: wrap;
    -moz-column-gap: 15px;
    column-gap: 15px;
    row-gap: 5px;
}

.civic-meta-icons-labels {
    display: none;
    margin-top: 0;
    margin-bottom: 5px;
    color: gray;
    font-size: 13px;
}

.civic_meta_icon_wrapper {
    display: flex;
    align-items: center;
    -moz-column-gap: 10px;
    column-gap: 10px;
}

.civic_meta_icon_wrapper .civic_meta_icon {
    display: flex;
    margin: 0;
    cursor: default;
}

.civic_prop_card_meta_wrap img.custom-meta-icon-image,
.civic_prop_card_meta_wrap svg {
    width: 15px;
    height: auto;
}

.civic-ultra-dark {
    fill: #0f806a;
}

.civic-ultra-light {
    fill: #dbf0fa;
}

.civic_prop_card_meta_wrap span {
    display: inline-block;
}

.civic_prop_card_meta_wrap .figure {
    color: #333;
    font-size: 13px;
    font-weight: 600;
}

.civic_prop_card_meta_wrap .label {
    color: gray;
    font-size: 13px;
    font-weight: 500;
}

.civic-price {
    font-size: 20px;
    font-weight: 700;
    color: #333;
    margin-bottom: 12px;
}

p.civic_prop_card__price {
    margin-bottom: 0;
    margin-top: 0;
    color: #808080;
    font-size: 14px;
}

.civic-meta-group {
    display: flex;
    gap: 16px;
}

.meta-item {
    display: flex;
    align-items: center;
    font-size: 13px;
    color: #555;
}

.meta-icon {
    width: 20px;
    height: 20px;
    margin-right: 4px;
}

.meta-label {
    margin-right: 4px;
}

.meta-value {
    font-weight: 600;
}

.civic-added {
    font-size: 12px;
    color: #999;
    margin-top: 12px;
}
</style>

<!-- Corporate Clients Section -->
<section class="area-padding d-none" id="clients">
    <div class="col-12">
        <div class="area-heading text-center">
            <h2 class="section-heading">Corporate Clients</h2>
        </div>
    </div>
    <div class="clients-grid">
        <img src="https://dummyimage.com/230x120/ccc/fff&text=BWAB 1" alt="BWAB 1 Logo">
        <img src="https://dummyimage.com/230x120/ccc/fff&text=BWAB 2" alt="BWAB 2 Logo">
        <img src="https://dummyimage.com/180x120/ccc/fff&text=Bkash" alt="Bkash Logo">
        <img src="https://dummyimage.com/120x120/ccc/fff&text=Client+4" alt="Client 4 Logo">
    </div>
</section>

<!-- Awards Section -->
<div class="area-padding bg-one">
    <section class="container bg-one" id="awards">
        <div class="col-12">
            <div class="area-heading text-center">
                <h2 class="section-heading">Awards &amp; Recognition</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-6 col-lg-6">
                <div class="single-tab">
                    <img class="lazyload" src="/themes/civicgroup/img/award_bwab1.jpg" alt="Civic Moon Hill" width="376"
                        height="428">
                    <div class="tab-inner">
                        <div class="single-heading">BWAB 1</div>
                        <p>MU with us in 2020 with Civic Moon Hill</p>
                        <span class="d-none" style="padding-top: 20px;">Details &gt;</span>
                    </div>
                    <a>
                        <span class="d-none">BWAB 1</span>
                    </a>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-6">
                <div class="single-tab">
                    <img class="lazyload" src="/themes/civicgroup/img/award_bwab2.jpg" alt="Civic Moon Hill" width="376"
                        height="428">
                    <div class="tab-inner">
                        <div class="single-heading">BWAB 2</div>
                        <p>MU with us in 2022 with Civic Hill Town</p>
                        <span class="d-none" style="padding-top: 20px;">Details &gt;</span>
                    </div>
                    <a>
                        <span class="d-none">BWAB 2</span>
                    </a>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Management Team Section -->
<section class="container area-padding" id="management">
    <div class="col-12">
        <div class="area-heading text-center">
            <h2 class="section-heading">Management Team</h2>
        </div>
    </div>
    <div class="row">
        <?php
		$metadata = array(
			'53' => array( // Adv. Majumdar
				'education' => "<b>B.S.S</b> <em>(Hons)</em> <b>M.S.S</b> <em>(Political Science)</em>\n <b>L.L.B L.L.M</b>",
				'experience' => '<b>Advocate</b> <em>at 8.12.2009</em>',
			),
			'2' => array( // Adv. Majumdar
				'education' => "<b>BA</b> - <em>Bachelor of Arts</em>",
				'experience' => '<b>15 years</b><em> of experience in Real Estate.</em>',
			),
			'57' => array( // Adv. Majumdar
				'education' => "<b>MBA</b> <em>- Master of Business Administration</em>",
				'experience' => '<b>15 years</b><em> of experience in Real Estate.</em>',
			),
		);

		$get_users = $db->orderBy('serial', 'ASC')
						->where('active', '1')
						->where('banned', '0')
						->where('management', '1')
						->get(T_USERS);

		foreach ($get_users as $value) {
			if ($value->user_id == 59) {
				continue;
			}
			
			// Ensure metadata exists for the user, else use default empty values
			$meta = $metadata[$value->user_id] ?? ['education' => '', 'experience' => ''];
		?>

        <div class="col-12 col-sm-6 col-lg-4">
            <div class="team-member">
                <img src="<?php echo htmlspecialchars($value->avatar); ?>" alt="User Image">
                <h4><?php echo htmlspecialchars(trim($value->first_name . ' ' . $value->last_name)); ?></h4>
                <p style="font-size: 16px;"><strong><?php echo htmlspecialchars($value->designation); ?></strong></p>
                <p><?php echo nl2br(htmlspecialchars_decode($meta['education'], ENT_QUOTES)); ?>
                    <hr style=" margin-top: 15px; margin-bottom: 10px; " />
                    <?php echo nl2br(htmlspecialchars_decode($meta['experience'], ENT_QUOTES)); ?>
                </p>
            </div>
        </div>

        <?php } ?>
    </div>
</section>

<section class="area-padding bg-one">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="area-heading text-center">
                    <span>Why Civic Group</span>
                    <h4 class="section-heading">Strength of the Company</h4>
                </div>
                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" type="button" data-toggle="collapse"
                                    data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Commitment to Building Code Compliance </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                            data-parent="#accordionExample">
                            <div class="card-body"> Quality comes first while setting priority for long-term or
                                short-term plans and day-to-day activities. From material to workmanship, we strive to
                                maintain quality in every stage in our building projects. With this great effort, we
                                have achieved the trust of our clients that fuel our sincere efforts. </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Uncompromised Safety </button>
                            </h5>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                            data-parent="#accordionExample">
                            <div class="card-body"> We design and develop buildings in line with the compliance
                                guidelines stated in the National Building Code. We never deviate from the standards and
                                best practices in the industry for providing safe addresses to our esteemed clients.
                                Therefore, our buildings are capable of withstanding the code-specified natural forces
                                like earthquakes. </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingThree">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Best Construction Materials </button>
                            </h5>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                            data-parent="#accordionExample">
                            <div class="card-body"> As a committed real estate company, we never compromise with the
                                quality of construction materials. We assure that price hike or any other situation in
                                the market don’t make us deviate from materials quality. Since we use the best
                                materials, our buildings become stronger, more sustainable without harming the
                                environment to a significant extent. </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFour">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                    On-Time Delivery </button>
                            </h5>
                        </div>
                        <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                            data-parent="#accordionExample">
                            <div class="card-body"> On-time delivery is one of our motos while dealing in real estate
                                business. We are always committed to satisfying you with on-time delivery service.
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingFive">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                    World-Class Consultants </button>
                            </h5>
                        </div>
                        <div id="collapseFive" class="collapse" aria-labelledby="headingFive"
                            data-parent="#accordionExample">
                            <div class="card-body"> We are endowed with world-class real estate consultants who ensure
                                the best service in the domain. </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingSix">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                    data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                    Prestigious Landmarks </button>
                            </h5>
                        </div>
                        <div id="collapseSix" class="collapse" aria-labelledby="headingSix"
                            data-parent="#accordionExample">
                            <div class="card-body"> Since the very beginning, Civic Group has been passing many
                                prestigious landmarks. One of the biggest landmarks that we have touched is evolving as
                                a trusted real estate development company in Bangladesh. </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="area-heading text-center">
                    <span>Key Business</span>
                    <h3 class="section-heading">Achievement [at a Glance]</h3>
                </div>
                <div class="content-box">
                    <p>As a quality-focused real estate company, we've achieved several notable milestones, including
                        earning the trust of our esteemed clients, recognition from industry experts, and acknowledgment
                        from international organizations. Our achievements include serving a significant number of
                        customers, completing numerous projects, and managing a substantial portfolio of ongoing and
                        upcoming ventures.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="area-padding bg-two d-none">
    <div class="container-fluid mid-container">
        <div class="row mb-80 justify-content-center">
            <div class="col-12  mb-25">
                <div class="area-heading text-center light">
                    <span>Would You Like</span>
                    <div class="h3 section-heading">To Have a Cup of Coffee!</div>
                </div>
            </div>
            <div class="single-contact-box">
                <div>
                    <img class="lazyload" src="/images/icons/buy-property-icon.png" alt="Interior Contact Info Icon"
                        width="42" height="35">
                </div>
                <div class="contact-info">
                    <span>Buy a Property</span>
                    <a href="tel:+8801711651551">
                        <i class="fas fa-phone"></i>01711 651551 <i class="fas fa-arrow-right"></i>1 </a>
                </div>
            </div>
            <div class="single-contact-box">
                <div>
                    <img class="lazyload" src="/images/icons/landlord-icon.png" alt="Landlord Contact Info" width="42"
                        height="35">
                </div>
                <div class="contact-info">
                    <span>Land Owners</span>
                    <a href="tel:+8801711651551">
                        <i class="fas fa-phone"></i>01711 651551 <i class="fas fa-arrow-right"></i>2 </a>
                </div>
            </div>
            <div class="single-contact-box">
                <div>
                    <img class="lazyload" src="/images/icons/customer-icon.png" alt="Customer Contact Info" width="42"
                        height="35">
                </div>
                <div class="contact-info">
                    <span>Customer Care</span>
                    <a href="tel:+8801711651551">
                        <i class="fas fa-phone"></i>01711 651551 <i class="fas fa-arrow-right"></i>3 </a>
                </div>
            </div>
            <div class="single-contact-box">
                <div>
                    <img class="lazyload" src="/images/icons/interior-icon.png" alt="Interior Contact Info" width="42"
                        height="35">
                </div>
                <div class="contact-info">
                    <span>Interior Design</span>
                    <a href="tel:+8801711651551">
                        <i class="fas fa-phone"></i>01711 651551 <i class="fas fa-arrow-right"></i>4 </a>
                </div>
            </div>
            <div class="single-contact-box">
                <div>
                    <img class="lazyload" src="/images/icons/construction.png" alt="Construction Icon" width="42"
                        height="35">
                </div>
                <div class="contact-info">
                    <span>Construction </span>
                    <a href="tel:+8801711651551">
                        <i class="fas fa-phone"></i>01711 651551 <i class="fas fa-arrow-right"></i>5 </a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
jQuery(function($) {
  const $container = $('.elementor-element-4c50e34a .elementor-slides-wrapper');
  const $slides    = $container.find('.elementor-slides');

  // Clean up Swiper classes
  $container.removeClass('swiper swiper-initialized swiper-horizontal swiper-pointer-events');
  $slides.removeClass('swiper-wrapper').find('.swiper-slide').each(function() {
    $(this).removeClass('swiper-slide').addClass('slick-slide');
  });

  // Initialize Slick
  $slides.slick({
    infinite:      true,
    autoplay:      true,
    autoplaySpeed: 2500,
    speed:         700,
    arrows:        true,
    dots:          true,
    pauseOnHover:  true,
    pauseOnFocus:  true,

    // reuse your existing nav & bullets
    prevArrow:    $container.find('.elementor-swiper-button-prev'),
    nextArrow:    $container.find('.elementor-swiper-button-next'),
    appendArrows: $container,
    appendDots:   $container.find('.swiper-pagination')
  });
});

document.addEventListener("DOMContentLoaded", function() {
    const sections = document.querySelectorAll("main section");
    const observer = new IntersectionObserver((entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add("in-view");
                observer.unobserve(entry.target);
            }
        });
    }, {
        // Trigger as soon as any part of the section is in view
        threshold: 0,
        // Expand the bottom boundary upward so that elements trigger before fully entering the viewport
        rootMargin: "0px 0px -100px 0px"
    });
    sections.forEach(section => observer.observe(section));
});

document.querySelectorAll('.nav-link').forEach(tab => {
    tab.addEventListener('click', function() {
        // Remove active class from all tabs
        document.querySelectorAll('.nav-link').forEach(t => t.classList.remove('active'));
        // Add active class to the clicked tab
        this.classList.add('active');
        // Get filter category
        let filter = this.getAttribute('data-filter');
        // Filter projects
        document.querySelectorAll('.project-item').forEach(item => {
            if (filter === 'all' || item.classList.contains(filter)) {
                item.style.display = 'block';
            } else {
                item.style.display = 'none';
            }
        });
    });
});
</script>