<div class="rh_property__floor_plans floor-plans margin-bottom-40px">
    <h3 class="rh_property__heading floor-plans-label">Floor Plans</h3>
    <div class="floor-plans-accordions">
        <div class="rh-floor-tabs-wrapper">
            <a class="rh-floor-plan-tab rh-current-tab" data-id="tab-1" href="#">Ground Floor </a>
            <a class="rh-floor-plan-tab " data-id="tab-2" href="#">MEZZANINE FLOOR</a>
            <a class="rh-floor-plan-tab " data-id="tab-3" href="#">TYPICAL FLOOR PLAN</a>
        </div>
        <div class="rh-floor-content-wrapper">
            <div class="rh-floor-plan rh-active-tab" data-id="tab-1">
                <div class="floor-plan-title-price">
                    <h4>Ground Floor </h4>
                </div>
                <div class="floor-plan-meta"></div>
                <div class="floor-plan-map">
                    <a href="https://fortress.com.bd/wp-content/uploads/2023/07/01-GROUND-FLOOR-PLAN_page-0001-scaled.jpg"
                        data-fancybox="floor-plans">
                        <img src="https://fortress.com.bd/wp-content/uploads/2023/07/01-GROUND-FLOOR-PLAN_page-0001-scaled.jpg"
                            alt="Ground Floor ">
                    </a>
                </div>
            </div>
            <div class="rh-floor-plan" data-id="tab-2">
                <div class="floor-plan-title-price">
                    <h4>MEZZANINE FLOOR</h4>
                </div>
                <div class="floor-plan-meta"></div>
                <div class="floor-plan-map">
                    <a href="https://fortress.com.bd/wp-content/uploads/2023/07/02-MEZANINE-FLOOR-PLAN_page-0001.jpg"
                        data-fancybox="floor-plans">
                        <img src="https://fortress.com.bd/wp-content/uploads/2023/07/02-MEZANINE-FLOOR-PLAN_page-0001.jpg"
                            alt="MEZZANINE FLOOR">
                    </a>
                </div>
            </div>
            <div class="rh-floor-plan" data-id="tab-3">
                <div class="floor-plan-title-price">
                    <h4>TYPICAL FLOOR PLAN</h4>
                </div>
                <div class="floor-plan-meta"></div>
                <div class="floor-plan-map">
                    <a href="https://fortress.com.bd/wp-content/uploads/2023/07/03-TYPICAL-FLOOR-PLAN_page-0001.jpg"
                        data-fancybox="floor-plans">
                        <img src="https://fortress.com.bd/wp-content/uploads/2023/07/03-TYPICAL-FLOOR-PLAN_page-0001.jpg"
                            alt="TYPICAL FLOOR PLAN">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>