<div class="rh_property__mc_wrap margin-bottom-40px">
    <h4 class="rh_property__heading">Mortgage Calculator</h4>
    <div class="rh_property__mc clearfix">
        <!-- Calculator left side -->
        <div class="mc_left_side">
            <!-- Term -->
            <div class="rh_mc_field">
                <label for="mc_term">Term</label>
                <div class="rh_form__item">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round" class="feather feather-calendar rh-ultra-stroke-dark"
                        viewBox="2 1 20 22">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                        <path d="M16 2v4M8 2v4M3 10h18"></path>
                    </svg>
                    <div class="dropdown bootstrap-select show-tick rh-ultra-select-dropdown mc_term inspiry_select_picker_trigger bs3"
                        style="width: 100%;">
                        <select id="mc_term" name="mc_term"
                            class="rh-ultra-select-dropdown mc_term inspiry_select_picker_trigger show-tick"
                            tabindex="-98">
                            <option value="30" selected="selected">30 Years Fixed</option>
                            <option value="20">20 Years Fixed</option>
                            <option value="15">15 Years Fixed</option>
                            <option value="10">10 Years Fixed</option>
                            <option value="5">5 Years Fixed</option>
                        </select>
                        <button type="button" class="btn dropdown-toggle btn-default" data-toggle="dropdown"
                            role="combobox" aria-owns="bs-select-13" aria-haspopup="listbox" aria-expanded="false"
                            data-id="mc_term" title="30 Years Fixed">
                            <div class="filter-option">
                                <div class="filter-option-inner">
                                    <div class="filter-option-inner-inner">30 Years Fixed</div>
                                </div>
                            </div>
                            <span class="bs-caret">
                                <span class="caret"></span>
                            </span>
                        </button>
                        <div class="dropdown-menu open">
                            <div class="inner open" role="listbox" id="bs-select-13" tabindex="-1">
                                <ul class="dropdown-menu inner " role="presentation"></ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Interest Rate -->
            <div class="rh_mc_field">
                <label for="mc_interest">Interest</label>
                <div class="rh_form__item rh-mc-slider-fields">
                    <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" viewBox="3 3 18 18">
                        <g>
                            <path fill="none" d="M0 0h24v24H0z"></path>
                        </g>
                        <g>
                            <path
                                d="M5 19h14V5H5v14zm8.03-11.94L14.09 6l1.41 1.41L16.91 6l1.06 1.06-1.41 1.41 1.41 1.41-1.06 1.06-1.41-1.4-1.41 1.41-1.06-1.06 1.41-1.41-1.41-1.42zM13 13.25h5v1.5h-5v-1.5zm0 2.5h5v1.5h-5v-1.5zM6.25 7.72h5v1.5h-5v-1.5zM6 14.5h2v-2h1.5v2h2V16h-2v2H8v-2H6v-1.5z"
                                opacity=".3"></path>
                            <path
                                d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V5h14v14z">
                            </path>
                            <path
                                d="M6.25 7.72h5v1.5h-5zM13 15.75h5v1.5h-5zm0-2.5h5v1.5h-5zM8 18h1.5v-2h2v-1.5h-2v-2H8v2H6V16h2zm6.09-7.05 1.41-1.41 1.41 1.41 1.06-1.06-1.41-1.42 1.41-1.41L16.91 6 15.5 7.41 14.09 6l-1.06 1.06 1.41 1.41-1.41 1.42z">
                            </path>
                        </g>
                    </svg>
                    <input id="mc_interest" class="mc_interset" type="text" value="3.5%">
                    <input class="mc_interset_slider" type="range" min="0" max="10" step="0.1" value="3.5">
                </div>
            </div>
            <!-- Home Price -->
            <div class="rh_mc_field">
                <label for="mc_home_price">Home Price</label>
                <div class="rh_form__item rh-mc-slider-fields">
                    <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" viewBox="2 2 20 20">
                        <path d="M0 0h24v24H0V0z" fill="none"></path>
                        <path
                            d="M12 4c-4.41 0-8 3.59-8 8s3.59 8 8 8 8-3.59 8-8-3.59-8-8-8zm1.23 13.33V19H10.9v-1.69c-1.5-.31-2.77-1.28-2.86-2.97h1.71c.09.92.72 1.64 2.32 1.64 1.71 0 2.1-.86 2.1-1.39 0-.73-.39-1.41-2.34-1.87-2.17-.53-3.66-1.42-3.66-3.21 0-1.51 1.22-2.48 2.72-2.81V5h2.34v1.71c1.63.39 2.44 1.63 2.49 2.97h-1.71c-.04-.97-.56-1.64-1.94-1.64-1.31 0-2.1.59-2.1 1.43 0 .73.57 1.22 2.34 1.67 1.77.46 3.66 1.22 3.66 3.42-.01 1.6-1.21 2.48-2.74 2.77z"
                            opacity=".3"></path>
                        <path
                            d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm.31-8.86c-1.77-.45-2.34-.94-2.34-1.67 0-.84.79-1.43 2.1-1.43 1.38 0 1.9.66 1.94 1.64h1.71c-.05-1.34-.87-2.57-2.49-2.97V5H10.9v1.69c-1.51.32-2.72 1.3-2.72 2.81 0 1.79 1.49 2.69 3.66 3.21 1.95.46 2.34 1.15 2.34 1.87 0 .53-.39 1.39-2.1 1.39-1.6 0-2.23-.72-2.32-1.64H8.04c.1 1.7 1.36 2.66 2.86 2.97V19h2.34v-1.67c1.52-.29 2.72-1.16 2.73-2.77-.01-2.2-1.9-2.96-3.66-3.42z">
                        </path>
                    </svg>
                    <input id="mc_home_price" class="mc_home_price" type="text" value="0">
                    <input class="mc_home_price_slider" type="range" min="100000" max="200000" step="1" value="0">
                    <input class="mc_currency_sign" type="hidden" value="BDT">
                    <input class="mc_sign_position" type="hidden" value="before">
                </div>
            </div>
            <!-- Down Payment -->
            <div class="rh_mc_field">
                <label for="mc_downpayment">Down Payment</label>
                <div class="rh_form__item rh-mc-slider-fields">
                    <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" viewBox="2 2 20 20">
                        <path d="M0 0h24v24H0V0z" fill="none"></path>
                        <path
                            d="M12 4c-4.41 0-8 3.59-8 8s3.59 8 8 8 8-3.59 8-8-3.59-8-8-8zm1.23 13.33V19H10.9v-1.69c-1.5-.31-2.77-1.28-2.86-2.97h1.71c.09.92.72 1.64 2.32 1.64 1.71 0 2.1-.86 2.1-1.39 0-.73-.39-1.41-2.34-1.87-2.17-.53-3.66-1.42-3.66-3.21 0-1.51 1.22-2.48 2.72-2.81V5h2.34v1.71c1.63.39 2.44 1.63 2.49 2.97h-1.71c-.04-.97-.56-1.64-1.94-1.64-1.31 0-2.1.59-2.1 1.43 0 .73.57 1.22 2.34 1.67 1.77.46 3.66 1.22 3.66 3.42-.01 1.6-1.21 2.48-2.74 2.77z"
                            opacity=".3"></path>
                        <path
                            d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm.31-8.86c-1.77-.45-2.34-.94-2.34-1.67 0-.84.79-1.43 2.1-1.43 1.38 0 1.9.66 1.94 1.64h1.71c-.05-1.34-.87-2.57-2.49-2.97V5H10.9v1.69c-1.51.32-2.72 1.3-2.72 2.81 0 1.79 1.49 2.69 3.66 3.21 1.95.46 2.34 1.15 2.34 1.87 0 .53-.39 1.39-2.1 1.39-1.6 0-2.23-.72-2.32-1.64H8.04c.1 1.7 1.36 2.66 2.86 2.97V19h2.34v-1.67c1.52-.29 2.72-1.16 2.73-2.77-.01-2.2-1.9-2.96-3.66-3.42z">
                        </path>
                    </svg>
                    <div class="rh-mc-fields-half">
                        <input id="mc_downpayment" class="mc_downpayment" type="text" value="0">
                        <input class="mc_downpayment_percent" type="text" value="10%">
                    </div>
                    <input class="mc_downpayment_slider" type="range" min="0" max="100" step="1" value="10">
                </div>
            </div>
        </div>
        <!-- End of the left side -->
        <div class="mc_right_side graph_circle">
            <div class="mc_term_interest">
                <div class="rh-mc-label-box">
                    <span class="mc_term_value rh-mc-value">30</span>
                    <span class="rh-mc-label"> Years Fixed </span>
                </div>
                <div class="rh-mc-label-box">
                    <span class="mc_interest_value rh-mc-value test">3.5</span>
                    <span class="rh-mc-percent">%</span>
                    <span class="rh-mc-label"> Interest </span>
                </div>
            </div>
            <div class="mc_cost_graph_circle">
                <svg class="mc_graph_svg" width="220" height="220" viewport="0 0 100 100">
                    <circle r="90" cx="110" cy="110" fill="transparent" stroke-dasharray="565.48" stroke-dashoffset="0">
                    </circle>
                    <circle class="mc_graph_hoa" r="90" cx="110" cy="110" fill="transparent" stroke-dasharray="565.48"
                        stroke-dashoffset="0"></circle>
                    <circle class="mc_graph_tax" r="90" cx="110" cy="110" fill="transparent" stroke-dasharray="565.48"
                        stroke-dashoffset="0"></circle>
                    <circle class="mc_graph_interest" r="90" cx="110" cy="110" fill="transparent"
                        stroke-dasharray="565.48" stroke-dashoffset="0"></circle>
                </svg>
                <div class="mc_cost_over_graph" data-cost-prefix=" per month">
                    <strong>BDT0</strong> per month
                </div>
            </div>
            <div class="mc_cost">
                <ul>
                    <li class="mc_cost_interest">Principle and Interest <span>BDT0</span>
                    </li>
                </ul>
                <input class="mc_cost_tax_value" type="hidden" value="0">
                <input class="mc_cost_hoa_value" type="hidden" value="0">
            </div>
        </div>
        <!-- End of the right side -->
    </div>
</div>