<div class="rh-ultra-property-sidebar">
    <aside class="rh-property-sidebar sidebar">
        <section class="widget rh_property_agent  ">
            <div class="rh-property-agent-enquiry-form rh-ultra-form">
                <form id="contact-form-id54" class="rh_widget_form contact-form" novalidate="novalidate">
                    <p class="rh_widget_form__row rh-ultra-form-field-wrapper">
                        <label for="rh-enquiry-name">
                            <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" height="24"
                                viewBox="0 0 24 24" width="24">
                                <path d="M0 0h24v24H0V0z" fill="none"></path>
                                <path
                                    d="M12 4c-4.41 0-8 3.59-8 8 0 1.82.62 3.49 1.64 4.83 1.43-1.74 4.9-2.33 6.36-2.33s4.93.59 6.36 2.33C19.38 15.49 20 13.82 20 12c0-4.41-3.59-8-8-8zm0 9c-1.94 0-3.5-1.56-3.5-3.5S10.06 6 12 6s3.5 1.56 3.5 3.5S13.94 13 12 13z"
                                    opacity=".3"></path>
                                <path
                                    d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zM7.07 18.28c.43-.9 3.05-1.78 4.93-1.78s4.51.88 4.93 1.78C15.57 19.36 13.86 20 12 20s-3.57-.64-4.93-1.72zm11.29-1.45c-1.43-1.74-4.9-2.33-6.36-2.33s-4.93.59-6.36 2.33C4.62 15.49 4 13.82 4 12c0-4.41 3.59-8 8-8s8 3.59 8 8c0 1.82-.62 3.49-1.64 4.83zM12 6c-1.94 0-3.5 1.56-3.5 3.5S10.06 13 12 13s3.5-1.56 3.5-3.5S13.94 6 12 6zm0 5c-.83 0-1.5-.67-1.5-1.5S11.17 8 12 8s1.5.67 1.5 1.5S12.83 11 12 11z">
                                </path>
                            </svg>
                        </label>
                        <input id="rh-enquiry-name" type="text" name="name" placeholder="Name"
                            class="required rh-ultra-field" title="* Please provide your name">
                    </p>
                    <!-- /.rh_widget_form__row -->
                    <p class="rh_widget_form__row rh-ultra-form-field-wrapper">
                        <label for="rh-enquiry-email">
                            <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" height="24" width="24">
                                <path d="M0 0h24v24H0V0z" fill="none"></path>
                                <path d="M20 8l-8 5-8-5v10h16zm0-2H4l8 4.99z" opacity=".3"></path>
                                <path
                                    d="M4 20h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2zM20 6l-8 4.99L4 6h16zM4 8l8 5 8-5v10H4V8z">
                                </path>
                            </svg>
                        </label>
                        <input id="rh-enquiry-email" type="text" name="email" placeholder="Email"
                            class="required rh-ultra-field" title="* Please provide valid email address">
                    </p>
                    <!-- /.rh_widget_form__row -->
                    <p class="rh_widget_form__row rh-ultra-form-field-wrapper">
                        <label for="rh-enquiry-phone">
                            <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" height="24"
                                viewBox="0 0 24 24" width="24">
                                <path d="M0 0h24v24H0V0z" fill="none"></path>
                                <path
                                    d="M19 17.47c-.88-.07-1.75-.22-2.6-.45l-1.19 1.19c1.2.41 2.48.67 3.8.75v-1.49zM6.54 5h-1.5c.09 1.32.35 2.59.75 3.8l1.2-1.2c-.24-.84-.39-1.71-.45-2.6z"
                                    opacity=".3"></path>
                                <path
                                    d="M20 21c.55 0 1-.45 1-1v-3.49c0-.55-.45-1-1-1-1.24 0-2.45-.2-3.57-.57-.1-.04-.21-.05-.31-.05-.26 0-.51.1-.71.29l-2.2 2.2c-2.83-1.45-5.15-3.76-6.59-6.59l2.2-2.2c.28-.28.36-.67.25-1.02C8.7 6.45 8.5 5.25 8.5 4c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17zm-3.6-3.98c.85.24 1.72.39 2.6.45v1.49c-1.32-.09-2.59-.35-3.8-.75l1.2-1.19zM5.03 5h1.5c.07.89.22 1.76.46 2.59l-1.2 1.2c-.41-1.2-.67-2.47-.76-3.79z">
                                </path>
                            </svg>
                        </label>
                        <input id="rh-enquiry-phone" type="text" name="phone" placeholder="Phone"
                            class="required rh-ultra-field" title="* Please provide valid phone number">
                    </p>
                    <!-- /.rh_widget_form__row -->
                    <p class="rh_widget_form__row rh-ultra-form-field-wrapper rh-ultra-form-textarea">
                        <label for="rh-enquiry-phone">
                            <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" height="24" width="24">
                                <path d="M0 0h24v24H0V0z" fill="none"></path>
                                <path d="M4 18l2-2h14V4H4z" opacity=".3"></path>
                                <path
                                    d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z">
                                </path>
                            </svg>
                        </label>
                        <textarea id="rh-enquiry-message" cols="40" rows="6" name="message" placeholder="Message"
                            class="required rh-ultra-field"
                            title="* Please provide your message">Hello, I am interested in [<?php echo $project->name; ?>]</textarea>
                    </p>
                    <!-- /.rh_widget_form__row -->
                    <input type="hidden" name="nonce" value="9f64eebd2e">
                    <input type="hidden" name="target" value="contact@civicgroupbd.com">
                    <input type="hidden" name="property_id" value="<?php echo $project->id; ?>">
                    <input type="hidden" name="action" value="send_message_to_agent">
                    <input type="hidden" name="property_title" value="<?php echo $project->name; ?>">
                    <input type="hidden" name="property_permalink" value="<?php echo $url; ?>">
                    <button type="submit" name="submit" class="rh-ultra-filled-button rh-ultra-button submit-button">
                        <span class="btn-text">Send Message</span>
                        <span id="ajax-loader-agent-form-id54" class="ajax-loader">
                            <!-- By Sam Herbert (@sherb), for everyone. More @ http://goo.gl/7AJzbL -->
                            <!-- Todo: add easing -->
                            <svg viewBox="0 0 57 57" xmlns="http://www.w3.org/2000/svg" width="57" height="57"
                                class="rh-ultra-stroke-dark">
                                <g fill="none" fill-rule="evenodd">
                                    <g transform="translate(1 1)" stroke-width="2">
                                        <circle class="rh-ultra-light" cx="5" cy="50" r="5">
                                            <animate attributeName="cy" begin="0s" dur="2.2s" values="50;5;50;50"
                                                calcMode="linear" repeatCount="indefinite">
                                            </animate>
                                            <animate attributeName="cx" begin="0s" dur="2.2s" values="5;27;49;5"
                                                calcMode="linear" repeatCount="indefinite"></animate>
                                        </circle>
                                        <circle class="rh-ultra-light" cx="27" cy="5" r="5">
                                            <animate attributeName="cy" begin="0s" dur="2.2s" from="5" to="5"
                                                values="5;50;50;5" calcMode="linear" repeatCount="indefinite">
                                            </animate>
                                            <animate attributeName="cx" begin="0s" dur="2.2s" from="27" to="27"
                                                values="27;49;5;27" calcMode="linear" repeatCount="indefinite">
                                            </animate>
                                        </circle>
                                        <circle class="rh-ultra-light" cx="49" cy="50" r="5">
                                            <animate attributeName="cy" begin="0s" dur="2.2s" values="50;50;5;50"
                                                calcMode="linear" repeatCount="indefinite">
                                            </animate>
                                            <animate attributeName="cx" from="49" to="49" begin="0s" dur="2.2s"
                                                values="49;5;27;49" calcMode="linear" repeatCount="indefinite">
                                            </animate>
                                        </circle>
                                    </g>
                                </g>
                            </svg>
                        </span>
                    </button>
                    <div class="error-container"></div>
                    <div class="message-container"></div>
                </form>
            </div>
            <!-- /.rh_property_agent__enquiry_form -->
        </section>
        <section id="featured_properties_widget-3" class="widget clearfix Featured_Properties_Widget d-none">
            <h3 class="title">Featured Properties</h3>
            <div class="ere-ultra-side-properties-wrapper">
                <div
                    class="ere-ultra-side-properties ere-ultra-properties-slider owl-carousel rh-ultra-slider-nav owl-loaded owl-drag">
                    <div class="owl-stage-outer">
                        <div class="owl-stage"
                            style="transform: translate3d(0px, 0px, 0px); transition: all; width: 772px;">
                            <div class="owl-item active" style="width: 375.594px; margin-right: 10px;">
                                <div class="ere-properties-slide item">
                                    <div class="rh-ultra-property-card-2 rh-ultra-grid-card-slide">
                                        <div class="rh-ultra-slide-widget-title">
                                            <h3 class="rh-ultra-property-title">
                                                <a href="https://fortress.com.bd/property/home-in-merrick-way/">Fortress
                                                    Valentina</a>
                                            </h3>
                                            <div class="rh-address-ultra">
                                                <a href="https://fortress.com.bd/property/home-in-merrick-way/">
                                                    <span class="rh-ultra-address-pin">
                                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="5 2 14 20">
                                                            <path
                                                                d="M12 4C9.2 4 7 6.2 7 9c0 2.9 2.9 7.2 5 9.9 2.1-2.7 5-7 5-9.9C17 6.2 14.8 4 12 4zM12 11.5c-1.4 0-2.5-1.1-2.5-2.5s1.1-2.5 2.5-2.5 2.5 1.1 2.5 2.5S13.4 11.5 12 11.5z"
                                                                fill="#1db2ff" class="rh-ultra-dark"
                                                                style="opacity:0.24;"></path>
                                                            <path
                                                                d="M12 2C8.1 2 5 5.1 5 9c0 5.3 7 13 7 13s7-7.8 7-13C19 5.1 15.9 2 12 2zM7 9c0-2.8 2.2-5 5-5s5 2.2 5 5c0 2.9-2.9 7.2-5 9.9C9.9 16.2 7 11.9 7 9z"
                                                                fill="#1db2ff" class="rh-ultra-dark"></path>
                                                            <circle cx="12" cy="9" r="2.5" fill="#1db2ff"
                                                                class="rh-ultra-dark"></circle>
                                                        </svg>
                                                    </span> N-Block; Bashundhara R/A </a>
                                            </div>
                                        </div>
                                        <div class="rh-ultra-card-thumb-wrapper">
                                            <div class="rh-ultra-property-card-thumb">
                                                <a class="rh-permalink"
                                                    href="https://fortress.com.bd/property/home-in-merrick-way/">
                                                    <img width="680" height="510"
                                                        src="https://fortress.com.bd/wp-content/uploads/2022/06/Velentina-15361536-680x510.png"
                                                        class="attachment-modern-property-child-slider size-modern-property-child-slider wp-post-image"
                                                        alt="Fortress Valentina || Fortress Group" decoding="async">
                                                </a>
                                            </div>
                                            <div class="rh-ultra-top-tags-box">
                                                <div class="rh-ultra-status-box">
                                                    <a href="https://fortress.com.bd/property-status/fcl/"
                                                        class="property-status-fcl rh-ultra-status">FCL</a>
                                                    <a href="https://fortress.com.bd/property-status/fcl-ongoing/"
                                                        class="property-status-fcl-ongoing rh-ultra-status">FCL
                                                        Ongoing</a>
                                                    <a href="https://fortress.com.bd/property-status/sold-out/"
                                                        class="property-status-sold-out rh-ultra-status">Sold
                                                        Out</a>
                                                    <span class="rh-ultra-featured"> Featured </span>
                                                    <span class="rh-ultra-hot"> Hot </span>
                                                </div>
                                                <div class="rh-ultra-year-built"> Build 2026 </div>
                                            </div>
                                            <div class="rh-ultra-bottom-box">
                                                <div class="rh-ultra-price-meta-box hide-ultra-price-postfix-separator">
                                                    <div class="rh_prop_card__priceLabel_ultra">
                                                        <p class="rh_prop_card__price_ultra"></p>
                                                    </div>
                                                </div>
                                                <div class="rh-ultra-action-buttons rh-ultra-action-dark hover-dark">
                                                    <span class="favorite-btn-wrap favorite-btn-45">
                                                        <span
                                                            class="favorite-placeholder highlight__red hide user_not_logged_in rh-ui-tooltip "
                                                            data-propertyid="45" title="Added to favorites">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M2.7 12.8C1.6 11.7 1 10.3 1 8.7s0.6-3 1.7-4.1C3.8 3.6 5.2 3 6.8 3c1.5 0 3 0.6 4.1 1.7 0.1 0.1 0.5 0.5 1.2 0.5 0.4 0 0.9-0.2 1.2-0.6 1.1-1.1 2.5-1.7 4-1.7s3 0.6 4.1 1.7C22.4 5.8 23 7.2 23 8.7s-0.6 3-1.7 4.1L12 21.6 2.7 12.8z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M17.3 4c1.3 0 2.5 0.5 3.4 1.4C21.5 6.3 22 7.5 22 8.7c0 1.3-0.5 2.4-1.4 3.3L12 20.2l-8.6-8.2C2.5 11.2 2 10 2 8.7c0-1.3 0.5-2.5 1.4-3.4C4.3 4.5 5.5 4 6.7 4 8 4 9.2 4.5 10.1 5.4 10.3 5.6 11 6.2 12 6.2c0.7 0 1.4-0.3 1.9-0.8C14.8 4.5 16 4 17.3 4M17.3 2c-1.7 0-3.5 0.7-4.8 2 -0.2 0.2-0.3 0.2-0.5 0.2 -0.3 0-0.5-0.2-0.5-0.2 -1.3-1.3-3-2-4.8-2S3.3 2.7 2 4c-2.6 2.6-2.6 6.9 0 9.5L12 23l10-9.5c2.6-2.6 2.6-6.9 0-9.5C20.7 2.7 19 2 17.3 2L17.3 2z">
                                                                </path>
                                                            </svg>
                                                        </span>
                                                        <a href="#"
                                                            class="favorite add-to-favorite user_not_logged_in rh-ui-tooltip "
                                                            data-propertyid="45" title="Add to favorites">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M2.7 12.8C1.6 11.7 1 10.3 1 8.7s0.6-3 1.7-4.1C3.8 3.6 5.2 3 6.8 3c1.5 0 3 0.6 4.1 1.7 0.1 0.1 0.5 0.5 1.2 0.5 0.4 0 0.9-0.2 1.2-0.6 1.1-1.1 2.5-1.7 4-1.7s3 0.6 4.1 1.7C22.4 5.8 23 7.2 23 8.7s-0.6 3-1.7 4.1L12 21.6 2.7 12.8z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M17.3 4c1.3 0 2.5 0.5 3.4 1.4C21.5 6.3 22 7.5 22 8.7c0 1.3-0.5 2.4-1.4 3.3L12 20.2l-8.6-8.2C2.5 11.2 2 10 2 8.7c0-1.3 0.5-2.5 1.4-3.4C4.3 4.5 5.5 4 6.7 4 8 4 9.2 4.5 10.1 5.4 10.3 5.6 11 6.2 12 6.2c0.7 0 1.4-0.3 1.9-0.8C14.8 4.5 16 4 17.3 4M17.3 2c-1.7 0-3.5 0.7-4.8 2 -0.2 0.2-0.3 0.2-0.5 0.2 -0.3 0-0.5-0.2-0.5-0.2 -1.3-1.3-3-2-4.8-2S3.3 2.7 2 4c-2.6 2.6-2.6 6.9 0 9.5L12 23l10-9.5c2.6-2.6 2.6-6.9 0-9.5C20.7 2.7 19 2 17.3 2L17.3 2z">
                                                                </path>
                                                            </svg>
                                                        </a>
                                                    </span>
                                                    <span class="add-to-compare-span compare-btn-45"
                                                        data-property-id="45" data-property-title="Fortress Valentina"
                                                        data-property-url="https://fortress.com.bd/property/home-in-merrick-way/"
                                                        data-property-image="https://fortress.com.bd/wp-content/uploads/2022/06/Velentina-15361536-488x326.png">
                                                        <span class="compare-placeholder highlight hide rh-ui-tooltip"
                                                            title="Added to compare">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M11.1 23l-3.4-3.4v-1.2l3.4-3.4h1l2 4 9 0h-9l-2 4H11.1zM12 9l-2-4L1 5h9l2-4 1 0 3.4 3.4v1.2L12.9 9H12z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M12.5 2l2.8 2.8v0.3L12.5 8l-1.4-2.9L11.1 5l0.1-0.1L12.5 2M11.5 16l1.4 2.9 0.1 0.1 -0.1 0.1L11.5 22l-2.8-2.8v-0.3L11.5 16M13.3 0h-2v0l-2 4H0v2h9.3l2 4h2l4-4V4L13.3 0 13.3 0zM12.7 14h-2l-4 4v2l4 4h2v0l2-4H24v-2h-9.3L12.7 14 12.7 14z">
                                                                </path>
                                                            </svg>
                                                        </span>
                                                        <a class="rh_trigger_compare add-to-compare rh-ui-tooltip"
                                                            href="https://fortress.com.bd/property/home-in-merrick-way/"
                                                            title="Add to compare">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M11.1 23l-3.4-3.4v-1.2l3.4-3.4h1l2 4 9 0h-9l-2 4H11.1zM12 9l-2-4L1 5h9l2-4 1 0 3.4 3.4v1.2L12.9 9H12z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M12.5 2l2.8 2.8v0.3L12.5 8l-1.4-2.9L11.1 5l0.1-0.1L12.5 2M11.5 16l1.4 2.9 0.1 0.1 -0.1 0.1L11.5 22l-2.8-2.8v-0.3L11.5 16M13.3 0h-2v0l-2 4H0v2h9.3l2 4h2l4-4V4L13.3 0 13.3 0zM12.7 14h-2l-4 4v2l4 4h2v0l2-4H24v-2h-9.3L12.7 14 12.7 14z">
                                                                </path>
                                                            </svg>
                                                        </a>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="owl-item" style="width: 375.594px; margin-right: 10px;">
                                <div class="ere-properties-slide item">
                                    <div class="rh-ultra-property-card-2 rh-ultra-grid-card-slide">
                                        <div class="rh-ultra-slide-widget-title">
                                            <h3 class="rh-ultra-property-title">
                                                <a
                                                    href="https://fortress.com.bd/property/villa-on-hollywood-boulevard/">Fortress
                                                    Pride</a>
                                            </h3>
                                            <div class="rh-address-ultra">
                                                <a class="rhea_trigger_map rhea_facnybox_trigger- "
                                                    data-rhea-map-source="rhea-map-source-"
                                                    data-rhea-map-location="25.894316988462,-80.160780084961,14"
                                                    data-rhea-map-title="Fortress Pride" data-rhea-map-price=""
                                                    data-rhea-map-thumb="https://fortress.com.bd/wp-content/uploads/2022/06/Pride-15361536-488x326.png"
                                                    href="https://fortress.com.bd/property/villa-on-hollywood-boulevard/">
                                                    <span class="rh-ultra-address-pin">
                                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="5 2 14 20">
                                                            <path
                                                                d="M12 4C9.2 4 7 6.2 7 9c0 2.9 2.9 7.2 5 9.9 2.1-2.7 5-7 5-9.9C17 6.2 14.8 4 12 4zM12 11.5c-1.4 0-2.5-1.1-2.5-2.5s1.1-2.5 2.5-2.5 2.5 1.1 2.5 2.5S13.4 11.5 12 11.5z"
                                                                fill="#1db2ff" class="rh-ultra-dark"
                                                                style="opacity:0.24;"></path>
                                                            <path
                                                                d="M12 2C8.1 2 5 5.1 5 9c0 5.3 7 13 7 13s7-7.8 7-13C19 5.1 15.9 2 12 2zM7 9c0-2.8 2.2-5 5-5s5 2.2 5 5c0 2.9-2.9 7.2-5 9.9C9.9 16.2 7 11.9 7 9z"
                                                                fill="#1db2ff" class="rh-ultra-dark"></path>
                                                            <circle cx="12" cy="9" r="2.5" fill="#1db2ff"
                                                                class="rh-ultra-dark"></circle>
                                                        </svg>
                                                    </span> Hatteras Lane, Hollywood, FL 33019, USA </a>
                                            </div>
                                        </div>
                                        <div class="rh-ultra-card-thumb-wrapper">
                                            <div class="rh-ultra-property-card-thumb">
                                                <a class="rh-permalink"
                                                    href="https://fortress.com.bd/property/villa-on-hollywood-boulevard/">
                                                    <img width="680" height="510"
                                                        src="https://fortress.com.bd/wp-content/uploads/2022/06/Pride-15361536-680x510.png"
                                                        class="attachment-modern-property-child-slider size-modern-property-child-slider wp-post-image"
                                                        alt="Fortress Pride || Fortress Group || Fortress Constructions Ltd"
                                                        decoding="async">
                                                </a>
                                            </div>
                                            <div class="rh-ultra-top-tags-box">
                                                <div class="rh-ultra-status-box">
                                                    <a href="https://fortress.com.bd/property-status/fcl/"
                                                        class="property-status-fcl rh-ultra-status">FCL</a>
                                                    <a href="https://fortress.com.bd/property-status/fcl-ongoing/"
                                                        class="property-status-fcl-ongoing rh-ultra-status">FCL
                                                        Ongoing</a>
                                                    <a href="https://fortress.com.bd/property-status/sold-out/"
                                                        class="property-status-sold-out rh-ultra-status">Sold
                                                        Out</a>
                                                    <span class="rh-ultra-featured"> Featured </span>
                                                    <span class="rh-ultra-hot"> Trendy </span>
                                                </div>
                                                <div class="rh-ultra-year-built"> Build 2029 </div>
                                            </div>
                                            <div class="rh-ultra-bottom-box">
                                                <div class="rh-ultra-price-meta-box hide-ultra-price-postfix-separator">
                                                    <div class="rh_prop_card__priceLabel_ultra">
                                                        <p class="rh_prop_card__price_ultra"></p>
                                                    </div>
                                                </div>
                                                <div class="rh-ultra-action-buttons rh-ultra-action-dark hover-dark">
                                                    <span class="favorite-btn-wrap favorite-btn-94">
                                                        <span
                                                            class="favorite-placeholder highlight__red hide user_not_logged_in rh-ui-tooltip "
                                                            data-propertyid="94" title="Added to favorites">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M2.7 12.8C1.6 11.7 1 10.3 1 8.7s0.6-3 1.7-4.1C3.8 3.6 5.2 3 6.8 3c1.5 0 3 0.6 4.1 1.7 0.1 0.1 0.5 0.5 1.2 0.5 0.4 0 0.9-0.2 1.2-0.6 1.1-1.1 2.5-1.7 4-1.7s3 0.6 4.1 1.7C22.4 5.8 23 7.2 23 8.7s-0.6 3-1.7 4.1L12 21.6 2.7 12.8z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M17.3 4c1.3 0 2.5 0.5 3.4 1.4C21.5 6.3 22 7.5 22 8.7c0 1.3-0.5 2.4-1.4 3.3L12 20.2l-8.6-8.2C2.5 11.2 2 10 2 8.7c0-1.3 0.5-2.5 1.4-3.4C4.3 4.5 5.5 4 6.7 4 8 4 9.2 4.5 10.1 5.4 10.3 5.6 11 6.2 12 6.2c0.7 0 1.4-0.3 1.9-0.8C14.8 4.5 16 4 17.3 4M17.3 2c-1.7 0-3.5 0.7-4.8 2 -0.2 0.2-0.3 0.2-0.5 0.2 -0.3 0-0.5-0.2-0.5-0.2 -1.3-1.3-3-2-4.8-2S3.3 2.7 2 4c-2.6 2.6-2.6 6.9 0 9.5L12 23l10-9.5c2.6-2.6 2.6-6.9 0-9.5C20.7 2.7 19 2 17.3 2L17.3 2z">
                                                                </path>
                                                            </svg>
                                                        </span>
                                                        <a href="#"
                                                            class="favorite add-to-favorite user_not_logged_in rh-ui-tooltip "
                                                            data-propertyid="94" title="Add to favorites">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M2.7 12.8C1.6 11.7 1 10.3 1 8.7s0.6-3 1.7-4.1C3.8 3.6 5.2 3 6.8 3c1.5 0 3 0.6 4.1 1.7 0.1 0.1 0.5 0.5 1.2 0.5 0.4 0 0.9-0.2 1.2-0.6 1.1-1.1 2.5-1.7 4-1.7s3 0.6 4.1 1.7C22.4 5.8 23 7.2 23 8.7s-0.6 3-1.7 4.1L12 21.6 2.7 12.8z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M17.3 4c1.3 0 2.5 0.5 3.4 1.4C21.5 6.3 22 7.5 22 8.7c0 1.3-0.5 2.4-1.4 3.3L12 20.2l-8.6-8.2C2.5 11.2 2 10 2 8.7c0-1.3 0.5-2.5 1.4-3.4C4.3 4.5 5.5 4 6.7 4 8 4 9.2 4.5 10.1 5.4 10.3 5.6 11 6.2 12 6.2c0.7 0 1.4-0.3 1.9-0.8C14.8 4.5 16 4 17.3 4M17.3 2c-1.7 0-3.5 0.7-4.8 2 -0.2 0.2-0.3 0.2-0.5 0.2 -0.3 0-0.5-0.2-0.5-0.2 -1.3-1.3-3-2-4.8-2S3.3 2.7 2 4c-2.6 2.6-2.6 6.9 0 9.5L12 23l10-9.5c2.6-2.6 2.6-6.9 0-9.5C20.7 2.7 19 2 17.3 2L17.3 2z">
                                                                </path>
                                                            </svg>
                                                        </a>
                                                    </span>
                                                    <span class="add-to-compare-span compare-btn-94"
                                                        data-property-id="94" data-property-title="Fortress Pride"
                                                        data-property-url="https://fortress.com.bd/property/villa-on-hollywood-boulevard/"
                                                        data-property-image="https://fortress.com.bd/wp-content/uploads/2022/06/Pride-15361536-488x326.png">
                                                        <span class="compare-placeholder highlight hide rh-ui-tooltip"
                                                            title="Added to compare">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M11.1 23l-3.4-3.4v-1.2l3.4-3.4h1l2 4 9 0h-9l-2 4H11.1zM12 9l-2-4L1 5h9l2-4 1 0 3.4 3.4v1.2L12.9 9H12z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M12.5 2l2.8 2.8v0.3L12.5 8l-1.4-2.9L11.1 5l0.1-0.1L12.5 2M11.5 16l1.4 2.9 0.1 0.1 -0.1 0.1L11.5 22l-2.8-2.8v-0.3L11.5 16M13.3 0h-2v0l-2 4H0v2h9.3l2 4h2l4-4V4L13.3 0 13.3 0zM12.7 14h-2l-4 4v2l4 4h2v0l2-4H24v-2h-9.3L12.7 14 12.7 14z">
                                                                </path>
                                                            </svg>
                                                        </span>
                                                        <a class="rh_trigger_compare add-to-compare rh-ui-tooltip"
                                                            href="https://fortress.com.bd/property/villa-on-hollywood-boulevard/"
                                                            title="Add to compare">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                                                height="24" viewBox="0 0 24 24">
                                                                <path class="rh-ultra-light"
                                                                    d="M11.1 23l-3.4-3.4v-1.2l3.4-3.4h1l2 4 9 0h-9l-2 4H11.1zM12 9l-2-4L1 5h9l2-4 1 0 3.4 3.4v1.2L12.9 9H12z">
                                                                </path>
                                                                <path class="rh-ultra-dark"
                                                                    d="M12.5 2l2.8 2.8v0.3L12.5 8l-1.4-2.9L11.1 5l0.1-0.1L12.5 2M11.5 16l1.4 2.9 0.1 0.1 -0.1 0.1L11.5 22l-2.8-2.8v-0.3L11.5 16M13.3 0h-2v0l-2 4H0v2h9.3l2 4h2l4-4V4L13.3 0 13.3 0zM12.7 14h-2l-4 4v2l4 4h2v0l2-4H24v-2h-9.3L12.7 14 12.7 14z">
                                                                </path>
                                                            </svg>
                                                        </a>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="owl-nav">
                        <button type="button" role="presentation" class="owl-prev disabled">
                            <i class="fas fa-caret-left"></i>
                        </button>
                        <button type="button" role="presentation" class="owl-next">
                            <i class="fas fa-caret-right"></i>
                        </button>
                    </div>
                </div>
                <div class="rh-ultra-widget-dots">
                    <button role="button" class="owl-dot active">
                        <span></span>
                    </button>
                    <button role="button" class="owl-dot">
                        <span></span>
                    </button>
                </div>
            </div>
        </section>
    </aside>
</div>