<span id="overview"></span>
<div class="rh-ultra-property-slider-wrapper">

    <div class="rh-ultra-property-slider-container">

        <!-- 2. MAIN SLIDER (just two slides; Slick will build the rest) -->
        <div class="rh-ultra-property-slider">
            <?php 
            foreach ($project_data['gallery'] as $image) { ?>
            <div class="rh-ultra-property-thumb-wrapper">
                <a class="rh-ultra-property-thumb" href="<?= $wo['config']['site_url'] . '/' . $image; ?>"
                    data-fancybox="gallery"
                    style="background-image:url('<?= $wo['config']['site_url'] . '/' . $image; ?>')"></a>
            </div>
            <?php } ?>
        </div>

        <!-- 3. INFO BOX (unchanged) -->
        <div class="rh-ultra-property-thumb-box">
            <div class="rh-ultra-property-thumb-container">
                <div class="rh-ultra-thumb-info-box">
                    <div class="page-head-inner">
                        <div class="rh-ultra-property-tags rh-property-title">
                        </div>
                        <div class="rh-ultra-property-title-price">
                            <h1 class="property-title"><?= $project->name; ?></h1>
                            <div class="rh-ultra-property-tag-wrapper">
                                <span class="rh-ultra-price  price-on-call "></span>
                            </div>
                        </div>
                        <p class="rh-ultra-property-address">
                            <span class="rh-ultra-address-pin"><svg xmlns="http://www.w3.org/2000/svg"
                                    viewBox="5 2 14 20">
                                    <path
                                        d="M12 4C9.2 4 7 6.2 7 9c0 2.9 2.9 7.2 5 9.9 2.1-2.7 5-7 5-9.9C17 6.2 14.8 4 12 4zM12 11.5c-1.4 0-2.5-1.1-2.5-2.5s1.1-2.5 2.5-2.5 2.5 1.1 2.5 2.5S13.4 11.5 12 11.5z"
                                        fill="#1db2ff" class="rh-ultra-dark" style="opacity:0.24;"></path>
                                    <path
                                        d="M12 2C8.1 2 5 5.1 5 9c0 5.3 7 13 7 13s7-7.8 7-13C19 5.1 15.9 2 12 2zM7 9c0-2.8 2.2-5 5-5s5 2.2 5 5c0 2.9-2.9 7.2-5 9.9C9.9 16.2 7 11.9 7 9z"
                                        fill="#1db2ff" class="rh-ultra-dark"></path>
                                    <circle cx="12" cy="9" r="2.5" fill="#1db2ff" class="rh-ultra-dark"></circle>
                                </svg>
                            </span>
                            <?= $project->location; ?>
                        </p>
                    </div>
                    <img class="only-for-print inspiry-qr-code"
                        src="https://chart.googleapis.com/chart?cht=qr&amp;chs=100x100&amp;chl=https://fortress.com.bd/property/fdl-majestic-iris/&amp;choe=UTF-8"
                        alt="FDL Majestic Iris">
                </div>
                <div class="rh-ultra-thumb-action-box rh-ultra-action-buttons rh-ultra-action-dark hover-dark">
                    <a href="javascript:window.print()" class="print rh-ui-tooltip" title="Print">
                        <svg class="rh-ultra-dark" xmlns="http://www.w3.org/2000/svg" height="24" width="24">
                            <path d="M0 0h24v24H0V0z" fill="none"></path>
                            <path d="M8 5h8v3H8z" opacity=".3"></path>
                            <circle cx="18" cy="11.5" r="1"></circle>
                            <path
                                d="M19 8h-1V3H6v5H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zM8 5h8v3H8V5zm8 14H8v-4h8v4zm4-4h-2v-2H6v2H4v-4c0-.55.45-1 1-1h14c.55 0 1 .45 1 1v4z">
                            </path>
                            <path
                                d="M6 13h12v2h2v-4c0-.55-.45-1-1-1H5c-.55 0-1 .45-1 1v4h2v-2zm12-2.5c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1z"
                                opacity=".3"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </div>

    </div><!-- /.rh-ultra-property-slider-container -->

    <!-- 4. THUMBNAIL NAV -->
    <div class="rh-ultra-property-carousel-wrapper">
        <div class="rh-ultra-property-carousel-box">
            <div class="rh-ultra-property-carousel rh-ultra-horizontal-carousel-trigger">
                <?php 
                        foreach ($project_data['gallery'] as $image) {
                    ?>

                <div class="slick-slide slick-active" style="width: 185px;" aria-hidden="false">
                    <div class="rh-ultra-property-carousel-thumb-box">
                        <span class="rh-ultra-property-carousel-thumb"
                            style="background-image: url(<?= $wo['config']['site_url'] . '/' . $image; ?>)"></span>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="rh-ultra-thumb-count">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                <style type="text/css">
                .rh-photo-st0 {
                    fill-rule: evenodd;
                    clip-rule: evenodd;
                }
                </style>
                <path class="rh-ultra-black rh-photo-st0"
                    d="M3 5h12c1.1 0 2 0.9 2 2v8c0 1.1-0.9 2-2 2H3c-1.1 0-2-0.9-2-2V7C1 5.9 1.9 5 3 5zM7.7 1h2.8c0.8-0.2 1.7 0.4 1.8 1.2 0 0 0 0.1 0 0.1L13 5H5l0.7-2.7C5.9 1.4 6.8 0.8 7.7 1zM9 7.4c2.2 0 4 1.8 4 4s-1.8 4-4 4 -4-1.8-4-4S6.8 7.4 9 7.4zM9 9c1.3 0 2.4 1.1 2.4 2.4s-1.1 2.4-2.4 2.4 -2.4-1.1-2.4-2.4S7.7 9 9 9L9 9zM8.2 2.6h1.6c0.4 0 0.8 0.4 0.7 0.9 0 0.4-0.3 0.7-0.7 0.7H8.2c-0.4 0-0.8-0.3-0.9-0.7 0-0.4 0.3-0.8 0.7-0.9C8.1 2.6 8.2 2.6 8.2 2.6z">
                </path>
            </svg> <span class="rh-slider-item-total"><?= count($project_data['gallery']); ?></span>
            <span class="rh-more-slides">Photos</span>
        </div>
    </div>

</div>
<?php


$load_count = count($project_data['gallery']) < 6 ? count($project_data['gallery']) : 1;
$load_count = Wo_IsMobile() == true ? 1 : $load_count;

?>
<!-- 6. Your initialization -->
<script>
jQuery(function($) {
    var $slider = $('.rh-ultra-property-slider'),
        $nav = $('.rh-ultra-property-carousel');

    if (typeof $.fn.slick !== 'function') {
        console.error('Slick not found');
        return;
    }

    if ($slider.hasClass('slick-initialized')) {
        $slider.slick('unslick');
    }
    if ($nav.hasClass('slick-initialized')) {
        $nav.slick('unslick');
    }

    $slider.slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        fade: true,
        infinite: true,
        prevArrow: '<button class="slick-prev slick-arrow">Previous</button>',
        nextArrow: '<button class="slick-next slick-arrow">Next</button>',
        asNavFor: '.rh-ultra-property-carousel'
    });

    $nav.slick({
        slidesToShow: <?= Wo_IsMobile() ? 3 : 6; ?>,
        slidesToScroll: <?= $load_count; ?>,
        arrows: false,
        asNavFor: '.rh-ultra-property-slider',
        dots: false,
        centerMode: false,
        focusOnSelect: true,
        infinite: false,
        draggable: true
    });
});
</script>