<!DOCTYPE html>
<html lang="<?php echo($wo['lang_attr']); ?>">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="/images/favicon.ico" rel="icon">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title><?php echo $wo['title'];?></title>
    <?php if ($wo['page'] == 'civic-moonhill') { ?>
    <!-- Primary Meta Tags -->
    <title>সিভিক মুনহিল আবাসন প্রকল্প | এককালীন রেজিস্ট্রিতে মূল্য ছাড়</title>
    <meta name="description" content="পূর্বাচল এশিয়ান হাইওয়ে সংলগ্ন সিভিক মুনহিল আবাসন প্রকল্প – এককালীন মূল্য ছাড় ও কিস্তির সুবিধা সহ। এখনই বিস্তারিত জানতে আবেদন করুন।" />
    <meta name="keywords" content="সিভিক মুনহিল, আবাসন প্রকল্প, পূর্বাচল, প্লট বিক্রয়, রিয়েল এস্টেট, আবাসিক প্লট" />
    <meta name="author" content="Aminul Islam Mehedi" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="product" />
    <meta property="product:price:amount" content="1450000" />
    <meta property="product:price:currency" content="BDT" />
    <meta property="og:title" content="সিভিক মুনহিল আবাসন প্রকল্প | এককালীন রেজিস্ট্রিতে মূল্য ছাড়" />
    <meta property="og:description" content="পূর্বাচল এশিয়ান হাইওয়ে সংলগ্ন সিভিক মুনহিল আবাসন প্রকল্প – এককালীন মূল্য ছাড় ও কিস্তির সুবিধা সহ। এখনই বিস্তারিত জানতে আবেদন করুন।" />
    <meta property="og:url" content="https://civicgroupbd.com/civic-moonhill" />
    <meta property="og:site_name" content="Civic Group" />
    <meta property="og:image" content="https://civicgroupbd.com/upload/photos/2025/07/aewioruoqiuroijkladfjasdiofjweiqur_ogmeta.jpg" />
    <meta property="og:image:alt" content="সিভিক মুনহিল আবাসন প্রকল্প - ভূমি বিক্রয়" />
    <meta property="og:locale" content="bn_BD" />
    
    
    
    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="সিভিক মুনহিল আবাসন প্রকল্প | এককালীন রেজিস্ট্রিতে মূল্য ছাড়" />
    <meta name="twitter:description" content="পূর্বাচল এশিয়ান হাইওয়ে সংলগ্ন সিভিক মুনহিল আবাসন প্রকল্প – এককালীন মূল্য ছাড় ও কিস্তির সুবিধা সহ। এখনই বিস্তারিত জানতে আবেদন করুন।" />
    <meta name="twitter:url" content="https://civicgroupbd.com/civic-moonhill" />
    <meta name="twitter:image" content="https://civicgroupbd.com/upload/photos/2025/07/aewioruoqiuroijkladfjasdiofjweiqur_ogmeta.jpg" />
    <meta name="twitter:image:alt" content="সিভিক মুনহিল আবাসন প্রকল্প - ভূমি বিক্রয়" />
    <meta name="twitter:site" content="@civicbd" />
    
    <!-- General SEO -->
    <link rel="canonical" href="https://civicgroupbd.com/civic-moonhill" />

    <?php } else { ?>
    
    <meta name="description"
        content="Civic Properties Ltd. is a leading land developer company in Dhaka. Having two township housing projects (Civic &amp; Moonhill) in Dhaka North, Bangladesh">
    <meta name="keywords"
        content="Real estate Developer Agency in Bangladesh, real estate company in Dhaka, developer company in Bangladesh, Developer company in Dhaka, Real estate developer company">
    <?php } ?>
        
    <link rel="shortcut icon" href="<?php echo $wo['config']['site_url']; ?>/images/favicon.ico">
    
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-FKJVDM9B9H"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-FKJVDM9B9H');
    </script>
    <?php //echo Wo_LoadPage('meta-data'); ?>
    <link rel="stylesheet"
        href="<?php echo $wo['config']['theme_url'];?>/css/style.css?version=<?php echo $wo['config']['version']; ?>"
        type="text/css">
    <link rel="stylesheet" href="<?php echo $wo['config']['theme_url'];?>/css/fontawesome6/css/all.min.css">

    <!---owl carousel--->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script
        src="<?php echo $wo['config']['theme_url'];?>/js/jquery.form.min.js?version=<?php echo $wo['config']['version']; ?>">
    </script>

    <!-- Slick CSS & JS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <!-- Leaflet CSS & JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

    <script src="<?php echo $wo['config']['theme_url'];?>/js/jquery.fancybox.min.js" defer="defer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="stylesheet"
        href="<?php echo $wo['config']['theme_url'];?>/css/property-view.css?version=<?php echo $wo['config']['version']; ?>"
        type="text/css">

    <script type="text/javascript">
    <?php echo $wo['config']['header_cc']; ?>

    function Wo_Ajax_Requests_File() {
        return "<?php echo $wo['config']['site_url'].'/requests.php';?>"
    }
    <?php if ($wo['config']['smooth_loading'] == 1 && $wo['loggedin'] == true) { ?>

    function Wo_Ajax_Requests_Filee() {
        return "<?php echo $wo['config']['site_url'].'/ajax_loading.php';?>"
    }
    <?php } ?>
    </script>
</head>

<body class="light-header">
    <input type="hidden" class="main_session" value="<?php echo Wo_CreateMainSession();?>">
    <div class="dvLayout">

        <?php
        echo ($wo['page'] == 'civic-moonhill') ? ' ' : Wo_LoadPage('header/content');?>

        <main><?php echo $wo['content'];?></main>

        <?php echo Wo_LoadPage('footer/content');?>

        <script defer="defer" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js">
        </script>
        <script defer="defer" src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.1/js/lightbox.min.js"></script>
        <script defer="defer" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
        </script>
        <script src="https://gijsroge.github.io/owl-carousel2-thumbs/assets/OwlCarousel2Thumbs.min.js" defer="defer">
        </script>
    </div>
</body>

</html>