<script type="application/ld+json">
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "<?php echo $wo['config']['siteTitle']; ?>",
		"url": "<?php echo $wo['config']['site_url']; ?>/",
		"sameAs": [
			"https://www.facebook.com/civicbd",
			"https://www.linkedin.com/company/civic-real-estate-limited/",
			"https://www.youtube.com/@civicrealestateltd3042"
		],
		"logo": "<?php echo $wo['config']['site_url']; ?>/img/logo-original.png",
		"priceRange": "$$$$",
		"image": "<?php echo $wo['config']['site_url']; ?>/images/og.jpg",
		"description": "<?php echo $wo['config']['siteTitle']; ?> is one of the most prominent land developer companies in Dhaka. Having two of the most sophisticated housing complex in north Dhaka.",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "Plot No-10, 3rd Floor, Taher Tower",
			"addressLocality": "Gulshan Circle-2",
			"addressRegion": "Dhaka",
			"postalCode": "1212",
			"addressCountry": "Bangladesh"
		},
		"geo": {
			"@type": "GeoCoordinates",
			"latitude": "23.7948579",
			"longitude": "90.4136003"
		},
		"hasMap": "https://goo.gl/maps/hJtv3ddjFcxGVgh66",
		"review": {
			"@type": "Review",
			"reviewRating": {
				"@type": "Rating",
				"ratingValue": "5",
				"bestRating": "5"
			},
			"author": {
				"@type": "Person",
				"name": "Rejaur RAHMAN"
			},
			"datePublished": "2022-06-01",
			"description": "One of the renowned Land Developer in Dhaka. They have two housing projects. Civic Moonhill. Hopefully both housing will be live shortly."
		},
		"aggregateRating": {
			"@type": "AggregateRating",
			"ratingValue": "4.1",
			"reviewCount": "37"
		},
		"openingHours": "Mo 09:30-17:30 Tu 09:30-17:30 We 09:30-17:30 Th 09:30-17:30 Sa 09:30-17:30 Su 09:30-17:30",
		"telephone": "+8801711651551"
	}
</script>
<meta property="og:url" content="<?php echo $wo['config']['site_url']; ?>/">
<meta property="og:type" content="website">
<meta property="og:title" content="A Land Development Company in Dhaka, Bangladesh | Civic Properties">
<meta property="og:description" content="<?php echo $wo['config']['siteTitle']; ?> is one of the most prominent land developer companies in Dhaka. Having two of the most sophisticated housing complex in north Dhaka.">
<meta property="og:image" content="<?php echo $wo['config']['site_url']; ?>/images/og.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="civicbd.com">
<meta property="twitter:url" content="<?php echo $wo['config']['site_url']; ?>/">
<meta name="twitter:title" content="A Land Development Company in Dhaka, Bangladesh | Civic Properties">
<meta name="twitter:description" content="<?php echo $wo['config']['siteTitle']; ?> is one of the most prominent land developer companies in Dhaka. Having two of the most sophisticated housing complex in north Dhaka.">
<meta name="twitter:image" content="<?php echo $wo['config']['site_url']; ?>/images/og.jpg">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#d00b13">