<!--start breadcrumb-->
<div class="page-breadcrumb d-flex align-items-center mb-3">
  <div class="breadcrumb-title pe-3"><?php echo $wo['title']; ?></div>
  <div class="ps-3 d-flex">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb mb-0 p-0 align-items-center">
		<li class="breadcrumb-item"><a href="javascript:;">
			<i class="fadeIn animated bx bx-calendar"></i>
		  </a>
		</li>
		<li class="breadcrumb-item active" aria-current="page">Register attandence</li>
	  </ol>
	</nav>
  </div>
</div>

	<div class="attandence mb-3 m-auto">
        <div class="select-panel d-flex justify-content-between">
			<select id="user_id" name="user_id" class="form-select w-auto wm-150" onchange="fetch_register_attendance()">
				<option value="999">All User</option>
				<?php 
					$get_users = $db->where('active', '1')->orderBy('serial', 'ASC')->get(T_USERS);
					
					foreach ($get_users as $userlist) {
						$first_name = cleanName($userlist->first_name);
						echo '<option' . (isset($_COOKIE['default_u_atten']) && $_COOKIE['default_u_atten'] == $userlist->user_id ? ' selected' : '') . " value='{$userlist->user_id}'>{$first_name} {$userlist->last_name}</option>";
					}
				?>
			</select>
            <!-- Use flatpickr for date selection -->
            <input class="form-select w-auto wm-150" type="text" id="date_start_end" name="date_start_end" placeholder="Select attendance date" readonly onchange="fetch_register_attendance()" value="<?php echo date('Y-m-d'); ?>" style=" max-width: 160px; ">
        </div>
    </div>
	<div class="attandence card m-auto">
		<div class="card-body">
			<div class="border p-3 rounded" id="registerAttendance">
		
			</div>
		</div>
    </div>

<script>
function fetch_register_attendance() {
    var date = document.getElementById('date_start_end');
    var user_id = document.getElementById('user_id');
	
	if (date == null || user_id == null) {
        return false;
    }
    $.ajax({
        type: "POST",
        url: Wo_Ajax_Requests_File() + '?f=attandence&s=register_attendance', // Ensure Wo_Ajax_Requests_File() returns the correct URL
		data: { date: date.value, user_id: user_id.value },
        success: function (response) {
            if (response['status'] == 200) {
				$("#registerAttendance").html(response['result']);
            }
        }
    });
}

$(document).ready(function() {
	fetch_register_attendance();
    // Initialize Flatpickr
    var flatpickrInstance = flatpickr('#date_start_end', {
        dateFormat: 'Y-m-d',
        altFormat: 'F j, Y',
        altInput: false,
        allowInput: false,
        clickOpens: true,
        onChange: function(selectedDates, dateStr, instance) {
            // Call fetch_register_attendance when the date changes
            fetch_register_attendance();
        },
        onReady: function(selectedDates, dateStr, instance) {
            // Add custom date range options to the Flatpickr container
            var datepickerContainer = instance.calendarContainer;

            var dateRangeOptions = [
                // { label: 'Today', range: [new Date(), new Date()] },
                // { label: 'Yesterday', range: [new Date(new Date().setDate(new Date().getDate() - 1)), new Date(new Date().setDate(new Date().getDate() - 1))] },
            ];

            dateRangeOptions.forEach(function(option) {
                var button = document.createElement('button');
                button.textContent = option.label;
                button.addEventListener('click', function() {
                    flatpickrInstance.setDate(option.range);
                    flatpickrInstance.close(); // Close Flatpickr instance
                    fetch_register_attendance();
                });

                datepickerContainer.prepend(button);
            });
        }
    });
});

</script>
<style>
<?php if (date('Y-m') != '2024-08') { ?>
.flatpickr-months, .flatpickr-innerContainer {
	//display: none !important;
}
<?php } ?>

.attandence { width: 100%; }
.intime_margin { margin: 10px 0; }
.image_margin { margin-bottom: 15px; }
@media (min-width:1200px) {
	.attandence { width: 75%; }
	.image_margin { margin-bottom: 0px; }
}
@media (min-width:1400px) {
	.attandence { width: 60%; }
	.image_margin { margin-bottom: 0px; }
}
.attandence .row:first-child {
    margin-top: 0px !important;
}
.attandence hr:last-child {
	display: none;
}
</style>