<?php if (Wo_IsAdmin() || Wo_IsModerator()) { ?>
<!--start breadcrumb-->
<div class="page-breadcrumb d-flex align-items-center mb-3">
	<div class="breadcrumb-title pe-3">General Settings</div>
</div>
<?php
		echo Wo_LoadManagePage('view_notif/content');
$user_id = Wo_UserIdForLogin(Wo_Secure($_GET['user']));
$wo['edit_user'] = Wo_UserData($user_id);
?>
<div class="mb-3 mt-5">
	<div class="row row-cols-auto g-3">
		<div class="col">
			<div class="attandence mb-3">
				<div class="select-panel d-flex justify-content-between">
					<select id="select_user_id" class="form-select w-auto wm-120 <?php echo (Wo_IsAdmin() || Wo_IsModerator()) ? '' : 'd-none'; ?>" onchange="DataTableReset()">
						<?php 
							$get_users = $db->orderBy('serial', 'ASC')->where('active', '1')->get(T_USERS);
							foreach ($get_users as $userlist) {
								$user   = Wo_UserData($userlist->user_id);
								$name = cleanName($user['name']);
								echo '<option' . ($_GET['user'] == $user['username'] ? ' selected' : '') . " value='{$user['username']}'>{$name}</option>";
							}
						?>
					</select>
				</div>
			</div>
			<div class="wrapper">
				<div class="login" style="display: flex;justify-content: center;">
						<div class="col-md-6">
						  <div class="login_innre">
							<div class="wo_settings_page wow_content">
								<form class="form-horizontal setting-change-password-form" method="post">
									<div class="setting-password-alert setting-update-alert"></div>
									<div class="row" style=" gap: 15px; ">
										<div class="wow_form_fields">
											<label for="app_version">App Version</label>
											<input id="app_version" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['app_version']; ?>" disabled>
										</div>
										<div class="wow_form_fields">
											<label for="user_id">User ID</label>
											<input id="user_id" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['user_id']; ?>" disabled>
										</div>
										<div class="wow_form_fields">
											<label for="username">Username</label>
											<input id="username" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['username']; ?>" disabled>
										</div>
										<div class="wow_form_fields">
											<label for="first_name"><?php echo $wo['lang']['first_name']; ?></label>
											<input id="first_name" name="first_name" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['first_name']; ?>">
										</div>
										<div class="wow_form_fields">
											<label for="last_name"><?php echo $wo['lang']['last_name']; ?></label>
											<input id="last_name" name="last_name" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['last_name']; ?>">
										</div>
										<div class="wow_form_fields">
											<label for="designation">Designation</label>
											<input id="designation" name="designation" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['designation']; ?>">
										</div>
										<div class="wow_form_fields">
											<label for="department">Department</label>
											<input id="department" name="department" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['department']; ?>">
										</div>
										<hr class="style-one" style=" margin-bottom: 0px; ">
										<div class="wow_form_fields">
											<label for="email"><?php echo $wo['lang']['email']; ?></label>
											<input id="email" name="email" type="email" class="form-control input-md" value="<?php echo $wo['edit_user']['email']; ?>">
										</div>
										<div class="wow_form_fields">
											<label for="phone">Phone</label>
											<input id="phone" name="phone" type="phone" class="form-control input-md" value="<?php echo $wo['edit_user']['phone_number']; ?>">
										</div>
										<div class="wow_form_fields">
											<label for="birthday">Date of Birth</label>
											<input id="birthday" name="birthday" type="text" class="form-control input-md datepicker" placeholder="YYYY-MM-DD" value="<?php echo $wo['edit_user']['birthday']; ?>" pattern="\d{4}-\d{2}-\d{2}" title="Enter a date in the format YYYY-MM-DD" required>
										</div>
										<div class="wow_form_fields">
											<label for="birthday">Joining Date</label>
											<input id="joining_date" name="joining_date" type="text" class="form-control input-md datepicker" placeholder="YYYY-MM-DD" value="<?php echo $wo['edit_user']['joining_date']; ?>" pattern="\d{4}-\d{2}-\d{2}" title="Enter a date in the format YYYY-MM-DD" required>
										</div>
										<?php if ($wo['edit_user']['user_id'] == $wo['edit_user']['user_id']) { ?>
										<div class="wow_form_fields">
											<label for="manage_pass">Two Factor Authentication</label>  
											<input id="manage_pass" name="manage_pass" type="password" class="form-control input-md" value="<?php echo $wo['edit_user']['manage_pass']; ?>">
										</div>
										<hr class="style-one" style=" margin-bottom: 0px; ">
										
										<div class="wow_form_fields">
											<label for="management">Is Management</label>
											<select id="management" name="management" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['management']; ?>">
												<option value="1" <?php echo ($wo['edit_user']['management'] == 1) ? 'selected' : ''; ?>>Yes</option>
												<option value="0" <?php echo ($wo['edit_user']['management'] == 0) ? 'selected' : ''; ?>>No</option>
												<option value="2" <?php echo ($wo['edit_user']['management'] == 2) ? 'selected' : ''; ?>>Out of List</option>
											</select>
										</div>
										<div class="wow_form_fields">
											<label for="exclude_attendance">Exclude Attendance</label>
											<select id="exclude_attendance" name="exclude_attendance" type="text" class="form-control input-md" value="<?php echo $wo['edit_user']['exclude_attendance']; ?>">
												<option value="1" <?php echo ($wo['edit_user']['exclude_attendance'] == 1) ? 'selected' : ''; ?>>Yes</option>
												<option value="0" <?php echo ($wo['edit_user']['exclude_attendance'] == 0) ? 'selected' : ''; ?>>No</option>
											</select>
										</div>
										
										<div class="wow_form_fields">
											<label for="serial">Serial</label>
											<input id="serial" name="serial" class="form-control input-md" value="<?php echo $wo['edit_user']['serial']; ?>">
										</div>
										
										<div class="wow_form_fields d-none">
											<label for="current_password"><?php echo $wo['lang']['current_password']; ?></label>  
											<input id="current_password" name="current_password" type="password" class="form-control input-md">
										</div>
										<?php } ?>
										<div class="wow_form_fields">
											<label for="new_password"><?php echo $wo['lang']['new_password']; ?></label>
											<input id="new_password" name="new_password" type="password" class="form-control input-md">
											<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
												<ul class="helper-text">
													<li class="length"><?php echo $wo['lang']['least_characters']; ?></li>
													<li class="lowercase"><?php echo $wo['lang']['contain_lowercase']; ?></li>
													<li class="uppercase"><?php echo $wo['lang']['contain_uppercase']; ?></li>
													<li class="special"><?php echo $wo['lang']['number_special']; ?></li>
												</ul>
											<?php } ?>
										</div>
										<div class="wow_form_fields d-none">
											<label for="repeat_new_password"><?php echo $wo['lang']['repeat_password']; ?></label>
											<input id="repeat_new_password" name="repeat_new_password" type="password" class="form-control input-md">
										</div>
									</div>
									<div class="wow_cset_cover" title="<?php echo $wo['lang']['cover']; ?>">
            							<div class="wow_cset_cover_hdr">
            								<span class="btn btn-file d-flex w-100" id="coverimage-holder" onclick="$('#cover').trigger('click'); return false;" style=" cursor: auto; ">
            									
            								</span>
            								<input type="file" class="hidden" id="cover" accept="image/jpeg" name="cover" disabled>
            							</div>
            							<div class="avatar-read" id="cover-form"><p></p></div>
            						</div>
            						<div class="wow_cset_avtr">
										<label for="signature">Signature (700x270)</label>
            							<div class="wow_cset_avtr_hdr wow_cset_avtr_hdr d-flex justify-content-center">
            								<span class="btn btn-file d-flex" id="avatarimage-holder" onclick="$('#avatar').trigger('click'); return false;" title="<?php echo $wo['lang']['avatar']; ?>">
            									<img src="<?php echo $wo['edit_user']['signature_url']; ?>" alt="Picture" style="height: 60px;width: 200px;">
            								</span>
            								<input type="file" class="hidden" id="avatar" accept="image/jpeg" name="signature">
            							</div>
            							<div class="avatar-read" id="photo-form"><p></p></div>
            						</div>
									<div class="text-center mt-3" style=" position: sticky; bottom: 15px; ">
										<button type="submit" class="btn btn-primary add_wow_loader w-100"><?php echo $wo['lang']['save']; ?></button>
									</div>

									<input type="hidden" name="user_id" value="<?php echo $wo['edit_user']['user_id'];?>">
									<input type="hidden" name="admin_mode" value="1">
									<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
							   </form>
							</div>
						</div>
					</div>
				</div>
				<div class="d-flex" style=" gap: 8px; flex-wrap: wrap; justify-content: center; ">
					<div class="text-center mt-3" onclick="zk_device_command('enable')">
						<button class="btn btn-success add_wow_loader">Enable</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('disable')">
						<button class="btn btn-danger add_wow_loader">Disable</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('open_door')">
						<button class="btn btn-primary add_wow_loader">Open Door</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('test_voice')">
						<button class="btn btn-success add_wow_loader">Test Voice</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('reboot')">
						<button class="btn btn-warning add_wow_loader">Reboot</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('power_off')">
						<button class="btn btn-danger add_wow_loader">Shutdown</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('reset')">
						<button class="btn btn-danger add_wow_loader">Reset</button>
					</div>
					<div class="text-center mt-3" onclick="zk_device_command('update_leave_days')">
						<button class="btn btn-danger add_wow_loader">Update Leave Days</button>
					</div>
				</div>
			</div>
		
		</div>
	</div>
</div>
<script type="text/javascript">
$(function() {	
    
	$(document).ready(function() {
		$("#avatar").on('change', function() {
		//Get count of selected files
		$("#avatarimage-holder").html("<img style='height: 60px;width: 200px;' src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
		$("#profile_details").fadeOut(200);
		$("#change_save").fadeIn(200);
		});
	});
	document.getElementById('select_user_id').addEventListener('change', function() {
		var url = "<?php echo(Wo_LoadManageLinkSettings('edit_user')); ?>?user=" + this.value;
		SMColibri.spa_load(url);
	});
	
	$('.datepicker').datepicker({
        dateFormat: 'yy-mm-dd',
        showOtherMonths: true,
        selectOtherMonths: true,
        changeMonth: true,
        changeYear: true
    });

  $('form.setting-change-password-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_password',
    beforeSend: function() {
    	<?php if ($wo['config']['password_complexity_system'] == 1) { ?>
    		if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
	    		$('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
	    	}
	    	else{
	    		$('.setting-password-alert').html("<div class='alert alert-danger'><?php echo($wo['lang']['complexity_requirements']) ?></div>");
	    		return false;
	    	}

        <?php } else{ ?>
        	$('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
        <?php } ?>


      
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
		$('html, body').animate({ scrollTop: 0 }, 500, function() {
		  // Then, set the alert message
		  $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
		  // Show the alert with fade-in effect
		  $('.alert-success').fadeIn('fast', function() {
			// Wait for 2.5 seconds, then fade out
			$(this).delay(2500).fadeOut(500, function() {
			  // Remove the alert from the DOM after it fades out
			  $(this).remove();
			  
			});
		  });
		});
        // $('form.setting-change-password-form').clearForm();
      } else if (data.errors) {
        var errors = data.errors.join("<br>");
        $('.setting-password-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.wo_settings_page').find('.add_wow_loader').removeClass('btn-loading');
    }
  });
});

<?php if ($wo['config']['password_complexity_system'] == 1) { ?>

(function(){
	var helperText = {
		charLength: document.querySelector('.helper-text .length'),
		lowercase: document.querySelector('.helper-text .lowercase'),
		uppercase: document.querySelector('.helper-text .uppercase'),
		special: document.querySelector('.helper-text .special')
	};
	var password = document.querySelector('#new_password');
	
	
	
	var pattern = {
		charLength: function() {
			if( password.value.length >= 6 ) {
				return true;
			}
		},
		lowercase: function() {
			var regex = /^(?=.*[a-z]).+$/; // Lowercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		uppercase: function() {
			var regex = /^(?=.*[A-Z]).+$/; // Uppercase character pattern

			if( regex.test(password.value) ) {
				return true;
			}
		},
		special: function() {
			var regex = /^(?=.*[0-9_\W]).+$/; // Special character or number pattern

			if( regex.test(password.value) ) {
				return true;
			}
		}   
	};
	
	// Listen for keyup action on password field
  function CheckCPassword() {
		$('.helper-text').slideDown('slow', function() {
  	    	
  	    });
		// Check that password is a minimum of 8 characters
		patternTest( pattern.charLength(), helperText.charLength );
		
		// Check that password contains a lowercase letter		
		patternTest( pattern.lowercase(), helperText.lowercase );
		
		// Check that password contains an uppercase letter
		patternTest( pattern.uppercase(), helperText.uppercase );
		
		// Check that password contains a number or special character
		patternTest( pattern.special(), helperText.special );
    
	    // Check that all requirements are fulfilled
	    if( hasClass(helperText.charLength, 'valid') &&
				  hasClass(helperText.lowercase, 'valid') && 
				 	hasClass(helperText.uppercase, 'valid') && 
				  hasClass(helperText.special, 'valid')
			) {
				addClass(password.parentElement, 'valid');
	    }
	    else {
	      removeClass(password.parentElement, 'valid');
	    }
	}
  password.addEventListener('keyup', CheckCPassword);
  password.addEventListener('input', CheckCPassword);
	
	function patternTest(pattern, response) {
		if(pattern) {
      addClass(response, 'valid');
    }
    else {
      removeClass(response, 'valid');
    }
	}
	
	function addClass(el, className) {
		if (el.classList) {
			el.classList.add(className);
		}
		else {
			el.className += ' ' + className;
		}
	}
	
	function removeClass(el, className) {
		if (el.classList)
				el.classList.remove(className);
			else
				el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
	}
	
	function hasClass(el, className) {
		if (el.classList) {
			console.log(el.classList);
			return el.classList.contains(className);	
		}
		else {
			new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);	
		}
	}
	
})();
<?php } ?>
</script>
<?php } else { echo Wo_LoadManagePage('permission-required/content'); } ?>