<footer class="footer-area">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-6 col-lg-4">
				<div class="footer-item">
					<a href="/" style=" font-size: 34px; margin-bottom: 5px; font-weight: 700; ">
						Civic Group
					</a>
					<div class="footer-social">
						<div class="footer-title">Follow us:</div>
						<ul>
							<li>
								<a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/AssureGroup" aria-label="Visit our facebook page" title="Visit our facebook page">
									<span class="d-none">facebook</span>
									<i class="fab fa-facebook-f"></i>
								</a>
							</li>
							<li>
								<a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/company/civic-group" aria-label="visit our linkedin page" title="Visit our linkedin page">
									<span class="d-none">linkedin</span>
									<i class="fab fa-linkedin-in"></i>
								</a>
							</li>
							<li>
								<a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/c/CIVICGROUPBangladesh" aria-label="visit 
								our youtube page" title="Visit our youtube page">
									<span class="d-none">youtube</span>
									<i class="fab fa-youtube-square"></i>
								</a>
							</li>
							<li>
								<a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/assuregroup/" aria-label="visit our instagram page" title="Visit our instagram page">
									<span class="d-none">instagram</span>
									<i class="fab fa-instagram"></i>
								</a>
							</li>
						</ul>
					</div>
					<ul class="list-info">
						<li>
							<div class="info-icon">
								<i class="fas fa-map-marker-alt"></i>
							</div>
							<div class="info-text">
								<a href="https://goo.gl/maps/TLiTUuqx8Sq4HrWd7" target="_blank" rel="noopener noreferrer">House: 4/6, Level: 5 & 6, Road: 9 <br/>Block: J, Baridhara, Dhaka 1212</a>
							</div>
						</li>
						<li>
							<div class="info-icon">
								<i class="fas fa-phone"></i>
							</div>
							<div class="info-text">
								<a href="tel:+8801711651551"> 01711 651551</a>
							</div>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-6 col-lg-4">
				<div class="footer-item">
					<div class="footer-title">Businesses</div>
					<ol class="footer-list">
						<li>
							<a href="/businesses/civic-development-and-design-ltd">Civic Real Estate Ltd </a>
						</li>
						<li>
							<a href="/businesses/civic-design-and-development-ltd">Civic Design &amp; Development Ltd </a>
						</li>
						<li>
							<a href="/businesses/civic-development-and-design-ltd">Civic Auto Mobile</a>
						</li>
						<li>
							<a href="/businesses/civic-development-and-design-ltd">Shad Fisheries</a>
						</li>
					</ol>
				</div>
			</div>
			<div class="col-md-12 col-lg-4">
				<div class="footer-item">
					<div class="footer-title">Property Collections</div>
					<div class="row footer-list-wrapper no-gutters">
						<div class="col-sm-4">
							<p>
								<a href="/properties/phases">Phases</a>
							</p>
							<ul class="footer-list">
								<li><a href="/properties/phases/ongoing">Ongoing</a></li>
							</ul>
						</div>
						<div class="col-sm-4 no-gutters">
							<p>
								<a href="/properties/types">Types</a>
							</p>
							<ul class="footer-list">
								<li><a href="/properties/types/residential">Residential</a></li>
							</ul>
						</div>
						<div class="col-sm-4 no-gutters ">
							<p>
								<a href="/properties/locations">Locations</a>
							</p>
							<ul class="footer-list">
								<li><a href="/properties/locations/dhanmondi.htm">Dhanmondi </a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="text-right footer-show-all">
					<a href="/properties" aria-label="apartment properties for sale">See More</a>
				</div>
			</div>
		</div>
		<div class="footer-copyright flex-column flex-lg-row text-lg-left">
			<ul class="footer-menu">
				<li>
					<a href="/about-us/privacy">Privacy Policy</a>
					<span>|</span>
				</li>
				<li>
					<a href="/sitemap">Sitemap</a>
				</li>
			</ul>
			<details>
				<summary>Copyright © 2024 Civic Group | All rights reserved. </summary>
				<p class="mb-0">All the content and creatives on this website are the property of Civic Group</p>
			</details>
			<div class="designby">Designed &amp; Developed by <a href="https://www.facebook.com/mr1aminul">Aminul Islam</a>. </div>
		</div>
	</div>
	<span class="backtotop">
		<span class="d-none">back to top</span>
		<i class="fas fa-chevron-up"></i>
	</span>
</footer>