<?= Wo_LoadManagePage('clients/includes/modals/cancel_purchase') ?>
<?= Wo_LoadManagePage('clients/includes/modals/transfer_purchase') ?>
<?= Wo_LoadManagePage('clients/includes/modals/suspend_purchase') ?>
<?= Wo_LoadManagePage('clients/includes/modals/purchase_history') ?>
<?= Wo_LoadManagePage('clients/includes/modals/installment_schedule') ?>
<?= Wo_LoadManagePage('clients/includes/modals/change_plot') ?>
<?= Wo_LoadManagePage('clients/includes/modals/print_schedule') ?>